DROP TABLE IF EXISTS all_options;
CREATE TABLE all_options(
	QuestionID INT,
	OptionID INT,
	OptionText VARCHAR(255)
);
INSERT INTO all_options VALUES (1,1,'UK');
INSERT INTO all_options VALUES (1,2,'US');
INSERT INTO all_options VALUES (2,1,'Male');
INSERT INTO all_options VALUES (2,2,'Female');
INSERT INTO all_options VALUES (4,1,'18-24');
INSERT INTO all_options VALUES (4,2,'25-34');
INSERT INTO all_options VALUES (4,3,'35-44');
INSERT INTO all_options VALUES (4,4,'45-54');
INSERT INTO all_options VALUES (4,5,'55-64');
INSERT INTO all_options VALUES (4,6,'65+');
INSERT INTO all_options VALUES (5,1,'Yes');
INSERT INTO all_options VALUES (5,2,'No, I don''t have any children');
INSERT INTO all_options VALUES (5,3,'No, my children don''t live with me');
INSERT INTO all_options VALUES (5,4,'Prefer not to answer');
INSERT INTO all_options VALUES (6,1,'Parent');
INSERT INTO all_options VALUES (6,2,'Non-Parent');
INSERT INTO all_options VALUES (7,1,'Employed - full-time (30 hours or more a week)');
INSERT INTO all_options VALUES (7,2,'Employed - part-time (8-29 hours a week)');
INSERT INTO all_options VALUES (7,3,'Self-employed - full-time (30 hours or more a week)');
INSERT INTO all_options VALUES (7,4,'Self-employed - part-time (8-29 hours a week)');
INSERT INTO all_options VALUES (7,5,'Retired');
INSERT INTO all_options VALUES (7,6,'Student');
INSERT INTO all_options VALUES (7,7,'Full-time parent, homemaker');
INSERT INTO all_options VALUES (7,8,'Not currently employed');
INSERT INTO all_options VALUES (7,9,'Prefer not to say');
INSERT INTO all_options VALUES (8,1,'Working');
INSERT INTO all_options VALUES (8,2,'Not working');
INSERT INTO all_options VALUES (8,3,'Prefer not to answer');
INSERT INTO all_options VALUES (9,1,'Before November 2019');
INSERT INTO all_options VALUES (9,2,'November 2019');
INSERT INTO all_options VALUES (9,3,'December 2019');
INSERT INTO all_options VALUES (9,4,'January 2020');
INSERT INTO all_options VALUES (9,5,'February 2020');
INSERT INTO all_options VALUES (9,6,'March 2020');
INSERT INTO all_options VALUES (9,7,'April 2020');
INSERT INTO all_options VALUES (9,8,'I haven''t heard anything about it');
INSERT INTO all_options VALUES (11,1,'1');
INSERT INTO all_options VALUES (11,2,'2');
INSERT INTO all_options VALUES (11,3,'3');
INSERT INTO all_options VALUES (11,4,'4');
INSERT INTO all_options VALUES (11,5,'5');
INSERT INTO all_options VALUES (11,6,'6');
INSERT INTO all_options VALUES (11,7,'7');
INSERT INTO all_options VALUES (11,8,'8');
INSERT INTO all_options VALUES (11,9,'9');
INSERT INTO all_options VALUES (11,10,'10');
INSERT INTO all_options VALUES (11,11,'11');
INSERT INTO all_options VALUES (12,1,'1');
INSERT INTO all_options VALUES (12,2,'2');
INSERT INTO all_options VALUES (12,3,'3');
INSERT INTO all_options VALUES (12,4,'4');
INSERT INTO all_options VALUES (12,5,'5');
INSERT INTO all_options VALUES (12,6,'6');
INSERT INTO all_options VALUES (12,7,'7');
INSERT INTO all_options VALUES (12,8,'8');
INSERT INTO all_options VALUES (12,9,'9');
INSERT INTO all_options VALUES (12,10,'10');
INSERT INTO all_options VALUES (12,11,'11');
INSERT INTO all_options VALUES (13,1,'1');
INSERT INTO all_options VALUES (13,2,'2');
INSERT INTO all_options VALUES (13,3,'3');
INSERT INTO all_options VALUES (13,4,'4');
INSERT INTO all_options VALUES (13,5,'5');
INSERT INTO all_options VALUES (13,6,'6');
INSERT INTO all_options VALUES (13,7,'7');
INSERT INTO all_options VALUES (13,8,'8');
INSERT INTO all_options VALUES (13,9,'9');
INSERT INTO all_options VALUES (13,10,'10');
INSERT INTO all_options VALUES (13,11,'11');
INSERT INTO all_options VALUES (15,1,'Very worried');
INSERT INTO all_options VALUES (15,2,'Somewhat worried');
INSERT INTO all_options VALUES (15,3,'Indifferent');
INSERT INTO all_options VALUES (15,4,'Somewhat happy');
INSERT INTO all_options VALUES (15,5,'Really happy');
INSERT INTO all_options VALUES (16,1,'Very worried');
INSERT INTO all_options VALUES (16,2,'Somewhat worried');
INSERT INTO all_options VALUES (16,3,'Indifferent');
INSERT INTO all_options VALUES (16,4,'Somewhat happy');
INSERT INTO all_options VALUES (16,5,'Really happy');
INSERT INTO all_options VALUES (17,1,'Very worried');
INSERT INTO all_options VALUES (17,2,'Somewhat worried');
INSERT INTO all_options VALUES (17,3,'Indifferent');
INSERT INTO all_options VALUES (17,4,'Somewhat happy');
INSERT INTO all_options VALUES (17,5,'Really happy');
INSERT INTO all_options VALUES (18,1,'Very worried');
INSERT INTO all_options VALUES (18,2,'Somewhat worried');
INSERT INTO all_options VALUES (18,3,'Indifferent');
INSERT INTO all_options VALUES (18,4,'Somewhat happy');
INSERT INTO all_options VALUES (18,5,'Really happy');
INSERT INTO all_options VALUES (19,1,'Very worried');
INSERT INTO all_options VALUES (19,2,'Somewhat worried');
INSERT INTO all_options VALUES (19,3,'Indifferent');
INSERT INTO all_options VALUES (19,4,'Somewhat happy');
INSERT INTO all_options VALUES (19,5,'Really happy');
INSERT INTO all_options VALUES (20,1,'Very worried');
INSERT INTO all_options VALUES (20,2,'Somewhat worried');
INSERT INTO all_options VALUES (20,3,'Indifferent');
INSERT INTO all_options VALUES (20,4,'Somewhat happy');
INSERT INTO all_options VALUES (20,5,'Really happy');
INSERT INTO all_options VALUES (21,1,'Very worried');
INSERT INTO all_options VALUES (21,2,'Somewhat worried');
INSERT INTO all_options VALUES (21,3,'Indifferent');
INSERT INTO all_options VALUES (21,4,'Somewhat happy');
INSERT INTO all_options VALUES (21,5,'Really happy');
INSERT INTO all_options VALUES (22,1,'Very worried');
INSERT INTO all_options VALUES (22,2,'Somewhat worried');
INSERT INTO all_options VALUES (22,3,'Indifferent');
INSERT INTO all_options VALUES (22,4,'Somewhat happy');
INSERT INTO all_options VALUES (22,5,'Really happy');
INSERT INTO all_options VALUES (23,1,'Very worried');
INSERT INTO all_options VALUES (23,2,'Somewhat worried');
INSERT INTO all_options VALUES (23,3,'Indifferent');
INSERT INTO all_options VALUES (23,4,'Somewhat happy');
INSERT INTO all_options VALUES (23,5,'Really happy');
INSERT INTO all_options VALUES (24,1,'Very worried');
INSERT INTO all_options VALUES (24,2,'Somewhat worried');
INSERT INTO all_options VALUES (24,3,'Indifferent');
INSERT INTO all_options VALUES (24,4,'Somewhat happy');
INSERT INTO all_options VALUES (24,5,'Really happy');
INSERT INTO all_options VALUES (25,1,'Very worried');
INSERT INTO all_options VALUES (25,2,'Somewhat worried');
INSERT INTO all_options VALUES (25,3,'Indifferent');
INSERT INTO all_options VALUES (25,4,'Somewhat happy');
INSERT INTO all_options VALUES (25,5,'Really happy');
INSERT INTO all_options VALUES (26,1,'Exercising or playing sports');
INSERT INTO all_options VALUES (26,2,'Yoga / meditation');
INSERT INTO all_options VALUES (26,3,'Gaming (console or mobile)');
INSERT INTO all_options VALUES (26,4,'Board games and jigsaws');
INSERT INTO all_options VALUES (26,5,'Arts and crafts');
INSERT INTO all_options VALUES (26,6,'Going to concerts or gigs');
INSERT INTO all_options VALUES (26,7,'Going to cultural events (e.g. theatre, museums etc.)');
INSERT INTO all_options VALUES (26,8,'Volunteering with a charity');
INSERT INTO all_options VALUES (26,9,'Dining out in restaurants');
INSERT INTO all_options VALUES (26,10,'Eating take away food');
INSERT INTO all_options VALUES (26,11,'Catching up with friends/family');
INSERT INTO all_options VALUES (26,12,'Reading books');
INSERT INTO all_options VALUES (26,13,'Watching TV shows/films');
INSERT INTO all_options VALUES (26,14,'Internet shopping');
INSERT INTO all_options VALUES (26,15,'Listening to music');
INSERT INTO all_options VALUES (26,16,'Listening to podcasts');
INSERT INTO all_options VALUES (26,17,'None of these');
INSERT INTO all_options VALUES (27,1,'Video calls with friends/family');
INSERT INTO all_options VALUES (27,2,'Online exercise classes');
INSERT INTO all_options VALUES (27,3,'Watch online theatre/plays');
INSERT INTO all_options VALUES (27,4,'Watch online gigs/concerts');
INSERT INTO all_options VALUES (27,5,'Play games online with friends');
INSERT INTO all_options VALUES (27,6,'Online video gaming');
INSERT INTO all_options VALUES (27,7,'Online quizzes');
INSERT INTO all_options VALUES (27,8,'Watching online videos');
INSERT INTO all_options VALUES (27,9,'Streaming films');
INSERT INTO all_options VALUES (27,10,'None of these');
INSERT INTO all_options VALUES (29,1,'Very worried');
INSERT INTO all_options VALUES (29,2,'Somewhat worried');
INSERT INTO all_options VALUES (29,3,'Indifferent');
INSERT INTO all_options VALUES (29,4,'Somewhat happy');
INSERT INTO all_options VALUES (29,5,'Really happy');
INSERT INTO all_options VALUES (30,1,'Very worried');
INSERT INTO all_options VALUES (30,2,'Somewhat worried');
INSERT INTO all_options VALUES (30,3,'Indifferent');
INSERT INTO all_options VALUES (30,4,'Somewhat happy');
INSERT INTO all_options VALUES (30,5,'Really happy');
INSERT INTO all_options VALUES (31,1,'Very worried');
INSERT INTO all_options VALUES (31,2,'Somewhat worried');
INSERT INTO all_options VALUES (31,3,'Indifferent');
INSERT INTO all_options VALUES (31,4,'Somewhat happy');
INSERT INTO all_options VALUES (31,5,'Really happy');
INSERT INTO all_options VALUES (32,1,'Very worried');
INSERT INTO all_options VALUES (32,2,'Somewhat worried');
INSERT INTO all_options VALUES (32,3,'Indifferent');
INSERT INTO all_options VALUES (32,4,'Somewhat happy');
INSERT INTO all_options VALUES (32,5,'Really happy');
INSERT INTO all_options VALUES (33,1,'Very worried');
INSERT INTO all_options VALUES (33,2,'Somewhat worried');
INSERT INTO all_options VALUES (33,3,'Indifferent');
INSERT INTO all_options VALUES (33,4,'Somewhat happy');
INSERT INTO all_options VALUES (33,5,'Really happy');
INSERT INTO all_options VALUES (34,1,'Very worried');
INSERT INTO all_options VALUES (34,2,'Somewhat worried');
INSERT INTO all_options VALUES (34,3,'Indifferent');
INSERT INTO all_options VALUES (34,4,'Somewhat happy');
INSERT INTO all_options VALUES (34,5,'Really happy');
INSERT INTO all_options VALUES (35,1,'Very worried');
INSERT INTO all_options VALUES (35,2,'Somewhat worried');
INSERT INTO all_options VALUES (35,3,'Indifferent');
INSERT INTO all_options VALUES (35,4,'Somewhat happy');
INSERT INTO all_options VALUES (35,5,'Really happy');
INSERT INTO all_options VALUES (36,1,'Very worried');
INSERT INTO all_options VALUES (36,2,'Somewhat worried');
INSERT INTO all_options VALUES (36,3,'Indifferent');
INSERT INTO all_options VALUES (36,4,'Somewhat happy');
INSERT INTO all_options VALUES (36,5,'Really happy');
INSERT INTO all_options VALUES (37,1,'Very worried');
INSERT INTO all_options VALUES (37,2,'Somewhat worried');
INSERT INTO all_options VALUES (37,3,'Indifferent');
INSERT INTO all_options VALUES (37,4,'Somewhat happy');
INSERT INTO all_options VALUES (37,5,'Really happy');
INSERT INTO all_options VALUES (38,1,'Very worried');
INSERT INTO all_options VALUES (38,2,'Somewhat worried');
INSERT INTO all_options VALUES (38,3,'Indifferent');
INSERT INTO all_options VALUES (38,4,'Somewhat happy');
INSERT INTO all_options VALUES (38,5,'Really happy');
INSERT INTO all_options VALUES (39,1,'Very worried');
INSERT INTO all_options VALUES (39,2,'Somewhat worried');
INSERT INTO all_options VALUES (39,3,'Indifferent');
INSERT INTO all_options VALUES (39,4,'Somewhat happy');
INSERT INTO all_options VALUES (39,5,'Really happy');
INSERT INTO all_options VALUES (40,1,'Not at all serious');
INSERT INTO all_options VALUES (40,2,'Not that serious');
INSERT INTO all_options VALUES (40,3,'Somewhat serious');
INSERT INTO all_options VALUES (40,4,'Very serious');
INSERT INTO all_options VALUES (41,1,'Before November 2019');
INSERT INTO all_options VALUES (41,2,'November 2019');
INSERT INTO all_options VALUES (41,3,'December 2019');
INSERT INTO all_options VALUES (41,4,'January 2020');
INSERT INTO all_options VALUES (41,5,'February 2020');
INSERT INTO all_options VALUES (41,6,'March 2020');
INSERT INTO all_options VALUES (41,7,'April 2020');
INSERT INTO all_options VALUES (41,8,'I haven''t heard anything about it');
INSERT INTO all_options VALUES (43,1,'1');
INSERT INTO all_options VALUES (43,2,'2');
INSERT INTO all_options VALUES (43,3,'3');
INSERT INTO all_options VALUES (43,4,'4');
INSERT INTO all_options VALUES (43,5,'5');
INSERT INTO all_options VALUES (43,6,'6');
INSERT INTO all_options VALUES (43,7,'7');
INSERT INTO all_options VALUES (43,8,'8');
INSERT INTO all_options VALUES (43,9,'9');
INSERT INTO all_options VALUES (43,10,'10');
INSERT INTO all_options VALUES (43,11,'11');
INSERT INTO all_options VALUES (44,1,'1');
INSERT INTO all_options VALUES (44,2,'2');
INSERT INTO all_options VALUES (44,3,'3');
INSERT INTO all_options VALUES (44,4,'4');
INSERT INTO all_options VALUES (44,5,'5');
INSERT INTO all_options VALUES (44,6,'6');
INSERT INTO all_options VALUES (44,7,'7');
INSERT INTO all_options VALUES (44,8,'8');
INSERT INTO all_options VALUES (44,9,'9');
INSERT INTO all_options VALUES (44,10,'10');
INSERT INTO all_options VALUES (44,11,'11');
INSERT INTO all_options VALUES (45,1,'1');
INSERT INTO all_options VALUES (45,2,'2');
INSERT INTO all_options VALUES (45,3,'3');
INSERT INTO all_options VALUES (45,4,'4');
INSERT INTO all_options VALUES (45,5,'5');
INSERT INTO all_options VALUES (45,6,'6');
INSERT INTO all_options VALUES (45,7,'7');
INSERT INTO all_options VALUES (45,8,'8');
INSERT INTO all_options VALUES (45,9,'9');
INSERT INTO all_options VALUES (45,10,'10');
INSERT INTO all_options VALUES (45,11,'11');
INSERT INTO all_options VALUES (46,1,'1');
INSERT INTO all_options VALUES (46,2,'2');
INSERT INTO all_options VALUES (46,3,'3');
INSERT INTO all_options VALUES (46,4,'4');
INSERT INTO all_options VALUES (46,5,'5');
INSERT INTO all_options VALUES (46,6,'6');
INSERT INTO all_options VALUES (46,7,'7');
INSERT INTO all_options VALUES (46,8,'8');
INSERT INTO all_options VALUES (46,9,'9');
INSERT INTO all_options VALUES (46,10,'10');
INSERT INTO all_options VALUES (46,11,'11');
INSERT INTO all_options VALUES (47,1,'1');
INSERT INTO all_options VALUES (47,2,'2');
INSERT INTO all_options VALUES (47,3,'3');
INSERT INTO all_options VALUES (47,4,'4');
INSERT INTO all_options VALUES (47,5,'5');
INSERT INTO all_options VALUES (47,6,'6');
INSERT INTO all_options VALUES (47,7,'7');
INSERT INTO all_options VALUES (47,8,'8');
INSERT INTO all_options VALUES (47,9,'9');
INSERT INTO all_options VALUES (47,10,'10');
INSERT INTO all_options VALUES (47,11,'11');
INSERT INTO all_options VALUES (48,1,'1');
INSERT INTO all_options VALUES (48,2,'2');
INSERT INTO all_options VALUES (48,3,'3');
INSERT INTO all_options VALUES (48,4,'4');
INSERT INTO all_options VALUES (48,5,'5');
INSERT INTO all_options VALUES (48,6,'6');
INSERT INTO all_options VALUES (48,7,'7');
INSERT INTO all_options VALUES (48,8,'8');
INSERT INTO all_options VALUES (48,9,'9');
INSERT INTO all_options VALUES (48,10,'10');
INSERT INTO all_options VALUES (48,11,'11');
INSERT INTO all_options VALUES (49,1,'1');
INSERT INTO all_options VALUES (49,2,'2');
INSERT INTO all_options VALUES (49,3,'3');
INSERT INTO all_options VALUES (49,4,'4');
INSERT INTO all_options VALUES (49,5,'5');
INSERT INTO all_options VALUES (49,6,'6');
INSERT INTO all_options VALUES (49,7,'7');
INSERT INTO all_options VALUES (49,8,'8');
INSERT INTO all_options VALUES (49,9,'9');
INSERT INTO all_options VALUES (49,10,'10');
INSERT INTO all_options VALUES (49,11,'11');
INSERT INTO all_options VALUES (50,1,'1');
INSERT INTO all_options VALUES (50,2,'2');
INSERT INTO all_options VALUES (50,3,'3');
INSERT INTO all_options VALUES (50,4,'4');
INSERT INTO all_options VALUES (50,5,'5');
INSERT INTO all_options VALUES (50,6,'6');
INSERT INTO all_options VALUES (50,7,'7');
INSERT INTO all_options VALUES (50,8,'8');
INSERT INTO all_options VALUES (50,9,'9');
INSERT INTO all_options VALUES (50,10,'10');
INSERT INTO all_options VALUES (50,11,'11');
INSERT INTO all_options VALUES (52,1,'Disagree strongly');
INSERT INTO all_options VALUES (52,2,'Disagree somewhat');
INSERT INTO all_options VALUES (52,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (52,4,'Agree somewhat');
INSERT INTO all_options VALUES (52,5,'Agree strongly');
INSERT INTO all_options VALUES (53,1,'Disagree strongly');
INSERT INTO all_options VALUES (53,2,'Disagree somewhat');
INSERT INTO all_options VALUES (53,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (53,4,'Agree somewhat');
INSERT INTO all_options VALUES (53,5,'Agree strongly');
INSERT INTO all_options VALUES (54,1,'Disagree strongly');
INSERT INTO all_options VALUES (54,2,'Disagree somewhat');
INSERT INTO all_options VALUES (54,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (54,4,'Agree somewhat');
INSERT INTO all_options VALUES (54,5,'Agree strongly');
INSERT INTO all_options VALUES (55,1,'Disagree strongly');
INSERT INTO all_options VALUES (55,2,'Disagree somewhat');
INSERT INTO all_options VALUES (55,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (55,4,'Agree somewhat');
INSERT INTO all_options VALUES (55,5,'Agree strongly');
INSERT INTO all_options VALUES (56,1,'Disagree strongly');
INSERT INTO all_options VALUES (56,2,'Disagree somewhat');
INSERT INTO all_options VALUES (56,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (56,4,'Agree somewhat');
INSERT INTO all_options VALUES (56,5,'Agree strongly');
INSERT INTO all_options VALUES (57,1,'Disagree strongly');
INSERT INTO all_options VALUES (57,2,'Disagree somewhat');
INSERT INTO all_options VALUES (57,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (57,4,'Agree somewhat');
INSERT INTO all_options VALUES (57,5,'Agree strongly');
INSERT INTO all_options VALUES (58,1,'Disagree strongly');
INSERT INTO all_options VALUES (58,2,'Disagree somewhat');
INSERT INTO all_options VALUES (58,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (58,4,'Agree somewhat');
INSERT INTO all_options VALUES (58,5,'Agree strongly');
INSERT INTO all_options VALUES (59,1,'Disagree strongly');
INSERT INTO all_options VALUES (59,2,'Disagree somewhat');
INSERT INTO all_options VALUES (59,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (59,4,'Agree somewhat');
INSERT INTO all_options VALUES (59,5,'Agree strongly');
INSERT INTO all_options VALUES (60,1,'Disagree strongly');
INSERT INTO all_options VALUES (60,2,'Disagree somewhat');
INSERT INTO all_options VALUES (60,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (60,4,'Agree somewhat');
INSERT INTO all_options VALUES (60,5,'Agree strongly');
INSERT INTO all_options VALUES (61,1,'Disagree strongly');
INSERT INTO all_options VALUES (61,2,'Disagree somewhat');
INSERT INTO all_options VALUES (61,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (61,4,'Agree somewhat');
INSERT INTO all_options VALUES (61,5,'Agree strongly');
INSERT INTO all_options VALUES (63,1,'Not at all confident');
INSERT INTO all_options VALUES (63,2,'Not very confident');
INSERT INTO all_options VALUES (63,3,'Indifferent');
INSERT INTO all_options VALUES (63,4,'Pretty confident');
INSERT INTO all_options VALUES (63,5,'Very confident');
INSERT INTO all_options VALUES (64,1,'Not at all confident');
INSERT INTO all_options VALUES (64,2,'Not very confident');
INSERT INTO all_options VALUES (64,3,'Indifferent');
INSERT INTO all_options VALUES (64,4,'Pretty confident');
INSERT INTO all_options VALUES (64,5,'Very confident');
INSERT INTO all_options VALUES (65,1,'Not at all confident');
INSERT INTO all_options VALUES (65,2,'Not very confident');
INSERT INTO all_options VALUES (65,3,'Indifferent');
INSERT INTO all_options VALUES (65,4,'Pretty confident');
INSERT INTO all_options VALUES (65,5,'Very confident');
INSERT INTO all_options VALUES (66,1,'Not at all confident');
INSERT INTO all_options VALUES (66,2,'Not very confident');
INSERT INTO all_options VALUES (66,3,'Indifferent');
INSERT INTO all_options VALUES (66,4,'Pretty confident');
INSERT INTO all_options VALUES (66,5,'Very confident');
INSERT INTO all_options VALUES (67,1,'Not at all confident');
INSERT INTO all_options VALUES (67,2,'Not very confident');
INSERT INTO all_options VALUES (67,3,'Indifferent');
INSERT INTO all_options VALUES (67,4,'Pretty confident');
INSERT INTO all_options VALUES (67,5,'Very confident');
INSERT INTO all_options VALUES (68,1,'Yes');
INSERT INTO all_options VALUES (68,2,'Maybe');
INSERT INTO all_options VALUES (68,3,'No');
INSERT INTO all_options VALUES (68,4,'Not Sure');
INSERT INTO all_options VALUES (69,1,'Ways to solve environmental issues');
INSERT INTO all_options VALUES (69,2,'Better contact with friends and family');
INSERT INTO all_options VALUES (69,3,'How to treat fellow human beings better');
INSERT INTO all_options VALUES (69,4,'How to tackle new viruses');
INSERT INTO all_options VALUES (69,5,'A different way of living');
INSERT INTO all_options VALUES (69,6,'A different way of working');
INSERT INTO all_options VALUES (69,7,'Other');
INSERT INTO all_options VALUES (71,1,'1');
INSERT INTO all_options VALUES (71,2,'2');
INSERT INTO all_options VALUES (71,3,'3');
INSERT INTO all_options VALUES (71,4,'4');
INSERT INTO all_options VALUES (71,5,'5');
INSERT INTO all_options VALUES (71,6,'6');
INSERT INTO all_options VALUES (71,7,'7');
INSERT INTO all_options VALUES (71,8,'8');
INSERT INTO all_options VALUES (71,9,'9');
INSERT INTO all_options VALUES (71,10,'10');
INSERT INTO all_options VALUES (71,11,'11');
INSERT INTO all_options VALUES (72,1,'1');
INSERT INTO all_options VALUES (72,2,'2');
INSERT INTO all_options VALUES (72,3,'3');
INSERT INTO all_options VALUES (72,4,'4');
INSERT INTO all_options VALUES (72,5,'5');
INSERT INTO all_options VALUES (72,6,'6');
INSERT INTO all_options VALUES (72,7,'7');
INSERT INTO all_options VALUES (72,8,'8');
INSERT INTO all_options VALUES (72,9,'9');
INSERT INTO all_options VALUES (72,10,'10');
INSERT INTO all_options VALUES (72,11,'11');
INSERT INTO all_options VALUES (73,1,'1');
INSERT INTO all_options VALUES (73,2,'2');
INSERT INTO all_options VALUES (73,3,'3');
INSERT INTO all_options VALUES (73,4,'4');
INSERT INTO all_options VALUES (73,5,'5');
INSERT INTO all_options VALUES (73,6,'6');
INSERT INTO all_options VALUES (73,7,'7');
INSERT INTO all_options VALUES (73,8,'8');
INSERT INTO all_options VALUES (73,9,'9');
INSERT INTO all_options VALUES (73,10,'10');
INSERT INTO all_options VALUES (73,11,'11');
INSERT INTO all_options VALUES (74,1,'1');
INSERT INTO all_options VALUES (74,2,'2');
INSERT INTO all_options VALUES (74,3,'3');
INSERT INTO all_options VALUES (74,4,'4');
INSERT INTO all_options VALUES (74,5,'5');
INSERT INTO all_options VALUES (74,6,'6');
INSERT INTO all_options VALUES (74,7,'7');
INSERT INTO all_options VALUES (74,8,'8');
INSERT INTO all_options VALUES (74,9,'9');
INSERT INTO all_options VALUES (74,10,'10');
INSERT INTO all_options VALUES (74,11,'11');
INSERT INTO all_options VALUES (75,1,'1');
INSERT INTO all_options VALUES (75,2,'2');
INSERT INTO all_options VALUES (75,3,'3');
INSERT INTO all_options VALUES (75,4,'4');
INSERT INTO all_options VALUES (75,5,'5');
INSERT INTO all_options VALUES (75,6,'6');
INSERT INTO all_options VALUES (75,7,'7');
INSERT INTO all_options VALUES (75,8,'8');
INSERT INTO all_options VALUES (75,9,'9');
INSERT INTO all_options VALUES (75,10,'10');
INSERT INTO all_options VALUES (75,11,'11');
INSERT INTO all_options VALUES (76,1,'1');
INSERT INTO all_options VALUES (76,2,'2');
INSERT INTO all_options VALUES (76,3,'3');
INSERT INTO all_options VALUES (76,4,'4');
INSERT INTO all_options VALUES (76,5,'5');
INSERT INTO all_options VALUES (76,6,'6');
INSERT INTO all_options VALUES (76,7,'7');
INSERT INTO all_options VALUES (76,8,'8');
INSERT INTO all_options VALUES (76,9,'9');
INSERT INTO all_options VALUES (76,10,'10');
INSERT INTO all_options VALUES (76,11,'11');
INSERT INTO all_options VALUES (77,1,'1');
INSERT INTO all_options VALUES (77,2,'2');
INSERT INTO all_options VALUES (77,3,'3');
INSERT INTO all_options VALUES (77,4,'4');
INSERT INTO all_options VALUES (77,5,'5');
INSERT INTO all_options VALUES (77,6,'6');
INSERT INTO all_options VALUES (77,7,'7');
INSERT INTO all_options VALUES (77,8,'8');
INSERT INTO all_options VALUES (77,9,'9');
INSERT INTO all_options VALUES (77,10,'10');
INSERT INTO all_options VALUES (77,11,'11');
INSERT INTO all_options VALUES (78,1,'Washing my hands regularly');
INSERT INTO all_options VALUES (78,2,'Using hand sanitiser');
INSERT INTO all_options VALUES (78,3,'Wearing a protective face mask');
INSERT INTO all_options VALUES (78,4,'Wearing protective gloves');
INSERT INTO all_options VALUES (78,5,'Keeping an extra distance from others');
INSERT INTO all_options VALUES (78,6,'Not visiting public places');
INSERT INTO all_options VALUES (78,7,'None of these');
INSERT INTO all_options VALUES (80,1,'Doing much less of');
INSERT INTO all_options VALUES (80,2,'Doing a little less of');
INSERT INTO all_options VALUES (80,3,'About the same');
INSERT INTO all_options VALUES (80,4,'Doing a little more of');
INSERT INTO all_options VALUES (80,5,'Doing much more of');
INSERT INTO all_options VALUES (80,6,'Stopped doing completely');
INSERT INTO all_options VALUES (81,1,'Doing much less of');
INSERT INTO all_options VALUES (81,2,'Doing a little less of');
INSERT INTO all_options VALUES (81,3,'About the same');
INSERT INTO all_options VALUES (81,4,'Doing a little more of');
INSERT INTO all_options VALUES (81,5,'Doing much more of');
INSERT INTO all_options VALUES (81,6,'Stopped doing completely');
INSERT INTO all_options VALUES (82,1,'Doing much less of');
INSERT INTO all_options VALUES (82,2,'Doing a little less of');
INSERT INTO all_options VALUES (82,3,'About the same');
INSERT INTO all_options VALUES (82,4,'Doing a little more of');
INSERT INTO all_options VALUES (82,5,'Doing much more of');
INSERT INTO all_options VALUES (82,6,'Stopped doing completely');
INSERT INTO all_options VALUES (83,1,'Doing much less of');
INSERT INTO all_options VALUES (83,2,'Doing a little less of');
INSERT INTO all_options VALUES (83,3,'About the same');
INSERT INTO all_options VALUES (83,4,'Doing a little more of');
INSERT INTO all_options VALUES (83,5,'Doing much more of');
INSERT INTO all_options VALUES (83,6,'Stopped doing completely');
INSERT INTO all_options VALUES (84,1,'Doing much less of');
INSERT INTO all_options VALUES (84,2,'Doing a little less of');
INSERT INTO all_options VALUES (84,3,'About the same');
INSERT INTO all_options VALUES (84,4,'Doing a little more of');
INSERT INTO all_options VALUES (84,5,'Doing much more of');
INSERT INTO all_options VALUES (84,6,'Stopped doing completely');
INSERT INTO all_options VALUES (85,1,'Doing much less of');
INSERT INTO all_options VALUES (85,2,'Doing a little less of');
INSERT INTO all_options VALUES (85,3,'About the same');
INSERT INTO all_options VALUES (85,4,'Doing a little more of');
INSERT INTO all_options VALUES (85,5,'Doing much more of');
INSERT INTO all_options VALUES (85,6,'Stopped doing completely');
INSERT INTO all_options VALUES (86,1,'Doing much less of');
INSERT INTO all_options VALUES (86,2,'Doing a little less of');
INSERT INTO all_options VALUES (86,3,'About the same');
INSERT INTO all_options VALUES (86,4,'Doing a little more of');
INSERT INTO all_options VALUES (86,5,'Doing much more of');
INSERT INTO all_options VALUES (86,6,'Stopped doing completely');
INSERT INTO all_options VALUES (87,1,'Doing much less of');
INSERT INTO all_options VALUES (87,2,'Doing a little less of');
INSERT INTO all_options VALUES (87,3,'About the same');
INSERT INTO all_options VALUES (87,4,'Doing a little more of');
INSERT INTO all_options VALUES (87,5,'Doing much more of');
INSERT INTO all_options VALUES (87,6,'Stopped doing completely');
INSERT INTO all_options VALUES (88,1,'Doing much less of');
INSERT INTO all_options VALUES (88,2,'Doing a little less of');
INSERT INTO all_options VALUES (88,3,'About the same');
INSERT INTO all_options VALUES (88,4,'Doing a little more of');
INSERT INTO all_options VALUES (88,5,'Doing much more of');
INSERT INTO all_options VALUES (88,6,'Stopped doing completely');
INSERT INTO all_options VALUES (89,1,'Doing much less of');
INSERT INTO all_options VALUES (89,2,'Doing a little less of');
INSERT INTO all_options VALUES (89,3,'About the same');
INSERT INTO all_options VALUES (89,4,'Doing a little more of');
INSERT INTO all_options VALUES (89,5,'Doing much more of');
INSERT INTO all_options VALUES (89,6,'Stopped doing completely');
INSERT INTO all_options VALUES (90,1,'Doing much less of');
INSERT INTO all_options VALUES (90,2,'Doing a little less of');
INSERT INTO all_options VALUES (90,3,'About the same');
INSERT INTO all_options VALUES (90,4,'Doing a little more of');
INSERT INTO all_options VALUES (90,5,'Doing much more of');
INSERT INTO all_options VALUES (90,6,'Stopped doing completely');
INSERT INTO all_options VALUES (91,1,'Doing much less of');
INSERT INTO all_options VALUES (91,2,'Doing a little less of');
INSERT INTO all_options VALUES (91,3,'About the same');
INSERT INTO all_options VALUES (91,4,'Doing a little more of');
INSERT INTO all_options VALUES (91,5,'Doing much more of');
INSERT INTO all_options VALUES (91,6,'Stopped doing completely');
INSERT INTO all_options VALUES (92,1,'Doing much less of');
INSERT INTO all_options VALUES (92,2,'Doing a little less of');
INSERT INTO all_options VALUES (92,3,'About the same');
INSERT INTO all_options VALUES (92,4,'Doing a little more of');
INSERT INTO all_options VALUES (92,5,'Doing much more of');
INSERT INTO all_options VALUES (92,6,'Stopped doing completely');
INSERT INTO all_options VALUES (93,1,'Doing much less of');
INSERT INTO all_options VALUES (93,2,'Doing a little less of');
INSERT INTO all_options VALUES (93,3,'About the same');
INSERT INTO all_options VALUES (93,4,'Doing a little more of');
INSERT INTO all_options VALUES (93,5,'Doing much more of');
INSERT INTO all_options VALUES (93,6,'Stopped doing completely');
INSERT INTO all_options VALUES (94,1,'Doing much less of');
INSERT INTO all_options VALUES (94,2,'Doing a little less of');
INSERT INTO all_options VALUES (94,3,'About the same');
INSERT INTO all_options VALUES (94,4,'Doing a little more of');
INSERT INTO all_options VALUES (94,5,'Doing much more of');
INSERT INTO all_options VALUES (94,6,'Stopped doing completely');
INSERT INTO all_options VALUES (95,1,'Doing much less of');
INSERT INTO all_options VALUES (95,2,'Doing a little less of');
INSERT INTO all_options VALUES (95,3,'About the same');
INSERT INTO all_options VALUES (95,4,'Doing a little more of');
INSERT INTO all_options VALUES (95,5,'Doing much more of');
INSERT INTO all_options VALUES (95,6,'Stopped doing completely');
INSERT INTO all_options VALUES (96,1,'Doing much less of');
INSERT INTO all_options VALUES (96,2,'Doing a little less of');
INSERT INTO all_options VALUES (96,3,'About the same');
INSERT INTO all_options VALUES (96,4,'Doing a little more of');
INSERT INTO all_options VALUES (96,5,'Doing much more of');
INSERT INTO all_options VALUES (96,6,'Stopped doing completely');
INSERT INTO all_options VALUES (97,1,'Doing much less of');
INSERT INTO all_options VALUES (97,2,'Doing a little less of');
INSERT INTO all_options VALUES (97,3,'About the same');
INSERT INTO all_options VALUES (97,4,'Doing a little more of');
INSERT INTO all_options VALUES (97,5,'Doing much more of');
INSERT INTO all_options VALUES (97,6,'Stopped doing completely');
INSERT INTO all_options VALUES (98,1,'Doing much less of');
INSERT INTO all_options VALUES (98,2,'Doing a little less of');
INSERT INTO all_options VALUES (98,3,'About the same');
INSERT INTO all_options VALUES (98,4,'Doing a little more of');
INSERT INTO all_options VALUES (98,5,'Doing much more of');
INSERT INTO all_options VALUES (98,6,'Stopped doing completely');
INSERT INTO all_options VALUES (99,1,'Doing much less of');
INSERT INTO all_options VALUES (99,2,'Doing a little less of');
INSERT INTO all_options VALUES (99,3,'About the same');
INSERT INTO all_options VALUES (99,4,'Doing a little more of');
INSERT INTO all_options VALUES (99,5,'Doing much more of');
INSERT INTO all_options VALUES (99,6,'Stopped doing completely');
INSERT INTO all_options VALUES (100,1,'Doing much less of');
INSERT INTO all_options VALUES (100,2,'Doing a little less of');
INSERT INTO all_options VALUES (100,3,'About the same');
INSERT INTO all_options VALUES (100,4,'Doing a little more of');
INSERT INTO all_options VALUES (100,5,'Doing much more of');
INSERT INTO all_options VALUES (100,6,'Stopped doing completely');
INSERT INTO all_options VALUES (101,1,'Doing much less of');
INSERT INTO all_options VALUES (101,2,'Doing a little less of');
INSERT INTO all_options VALUES (101,3,'About the same');
INSERT INTO all_options VALUES (101,4,'Doing a little more of');
INSERT INTO all_options VALUES (101,5,'Doing much more of');
INSERT INTO all_options VALUES (101,6,'Stopped doing completely');
INSERT INTO all_options VALUES (102,1,'Doing much less of');
INSERT INTO all_options VALUES (102,2,'Doing a little less of');
INSERT INTO all_options VALUES (102,3,'About the same');
INSERT INTO all_options VALUES (102,4,'Doing a little more of');
INSERT INTO all_options VALUES (102,5,'Doing much more of');
INSERT INTO all_options VALUES (102,6,'Stopped doing completely');
INSERT INTO all_options VALUES (103,1,'Doing much less of');
INSERT INTO all_options VALUES (103,2,'Doing a little less of');
INSERT INTO all_options VALUES (103,3,'About the same');
INSERT INTO all_options VALUES (103,4,'Doing a little more of');
INSERT INTO all_options VALUES (103,5,'Doing much more of');
INSERT INTO all_options VALUES (103,6,'Stopped doing completely');
INSERT INTO all_options VALUES (104,1,'Doing much less of');
INSERT INTO all_options VALUES (104,2,'Doing a little less of');
INSERT INTO all_options VALUES (104,3,'About the same');
INSERT INTO all_options VALUES (104,4,'Doing a little more of');
INSERT INTO all_options VALUES (104,5,'Doing much more of');
INSERT INTO all_options VALUES (104,6,'Stopped doing completely');
INSERT INTO all_options VALUES (105,1,'Exercising or playing sports');
INSERT INTO all_options VALUES (105,2,'Yoga / meditation');
INSERT INTO all_options VALUES (105,3,'Gaming (console or mobile)');
INSERT INTO all_options VALUES (105,4,'Board games and jigsaws');
INSERT INTO all_options VALUES (105,5,'Arts and crafts');
INSERT INTO all_options VALUES (105,6,'Going to concerts or gigs');
INSERT INTO all_options VALUES (105,7,'Going to cultural events (e.g. theatre, museums etc.)');
INSERT INTO all_options VALUES (105,8,'Volunteering with a charity');
INSERT INTO all_options VALUES (105,9,'Dining out in restaurants');
INSERT INTO all_options VALUES (105,10,'Eating take away food');
INSERT INTO all_options VALUES (105,11,'Catching up with friends/family');
INSERT INTO all_options VALUES (105,12,'Reading books');
INSERT INTO all_options VALUES (105,13,'Watching TV shows/films');
INSERT INTO all_options VALUES (105,14,'Internet shopping');
INSERT INTO all_options VALUES (105,15,'Listening to music');
INSERT INTO all_options VALUES (105,16,'Listening to podcasts');
INSERT INTO all_options VALUES (105,17,'Video calls with friends/family');
INSERT INTO all_options VALUES (105,18,'Online exercise classes');
INSERT INTO all_options VALUES (105,19,'Watch online theatre/plays');
INSERT INTO all_options VALUES (105,20,'Watch online gigs/concerts');
INSERT INTO all_options VALUES (105,21,'Play games online with friends');
INSERT INTO all_options VALUES (105,22,'Online video gaming');
INSERT INTO all_options VALUES (105,23,'Online quizzes');
INSERT INTO all_options VALUES (105,24,'Watching online videos');
INSERT INTO all_options VALUES (105,25,'Streaming films');
INSERT INTO all_options VALUES (106,1,'Bulk buying food items to stock up');
INSERT INTO all_options VALUES (106,2,'Bulk buying non-food items to stock up');
INSERT INTO all_options VALUES (106,3,'Getting food deliveries from online retailers');
INSERT INTO all_options VALUES (106,4,'Signing up to food delivery subscription services');
INSERT INTO all_options VALUES (106,5,'Going to the supermarket');
INSERT INTO all_options VALUES (106,6,'Going to the local ''corner'' shop');
INSERT INTO all_options VALUES (106,7,'Ordering non-food items from online retailers (e.g. Amazon)');
INSERT INTO all_options VALUES (106,8,'Ordering takeaways / deliveries from local restaurants');
INSERT INTO all_options VALUES (106,9,'None of these');
INSERT INTO all_options VALUES (108,1,'Doing much less of');
INSERT INTO all_options VALUES (108,2,'Doing a little less of');
INSERT INTO all_options VALUES (108,3,'About the same');
INSERT INTO all_options VALUES (108,4,'Doing a little more of');
INSERT INTO all_options VALUES (108,5,'Doing much more of');
INSERT INTO all_options VALUES (109,1,'Doing much less of');
INSERT INTO all_options VALUES (109,2,'Doing a little less of');
INSERT INTO all_options VALUES (109,3,'About the same');
INSERT INTO all_options VALUES (109,4,'Doing a little more of');
INSERT INTO all_options VALUES (109,5,'Doing much more of');
INSERT INTO all_options VALUES (110,1,'Doing much less of');
INSERT INTO all_options VALUES (110,2,'Doing a little less of');
INSERT INTO all_options VALUES (110,3,'About the same');
INSERT INTO all_options VALUES (110,4,'Doing a little more of');
INSERT INTO all_options VALUES (110,5,'Doing much more of');
INSERT INTO all_options VALUES (111,1,'Doing much less of');
INSERT INTO all_options VALUES (111,2,'Doing a little less of');
INSERT INTO all_options VALUES (111,3,'About the same');
INSERT INTO all_options VALUES (111,4,'Doing a little more of');
INSERT INTO all_options VALUES (111,5,'Doing much more of');
INSERT INTO all_options VALUES (112,1,'Doing much less of');
INSERT INTO all_options VALUES (112,2,'Doing a little less of');
INSERT INTO all_options VALUES (112,3,'About the same');
INSERT INTO all_options VALUES (112,4,'Doing a little more of');
INSERT INTO all_options VALUES (112,5,'Doing much more of');
INSERT INTO all_options VALUES (113,1,'Doing much less of');
INSERT INTO all_options VALUES (113,2,'Doing a little less of');
INSERT INTO all_options VALUES (113,3,'About the same');
INSERT INTO all_options VALUES (113,4,'Doing a little more of');
INSERT INTO all_options VALUES (113,5,'Doing much more of');
INSERT INTO all_options VALUES (114,1,'Doing much less of');
INSERT INTO all_options VALUES (114,2,'Doing a little less of');
INSERT INTO all_options VALUES (114,3,'About the same');
INSERT INTO all_options VALUES (114,4,'Doing a little more of');
INSERT INTO all_options VALUES (114,5,'Doing much more of');
INSERT INTO all_options VALUES (115,1,'Doing much less of');
INSERT INTO all_options VALUES (115,2,'Doing a little less of');
INSERT INTO all_options VALUES (115,3,'About the same');
INSERT INTO all_options VALUES (115,4,'Doing a little more of');
INSERT INTO all_options VALUES (115,5,'Doing much more of');
INSERT INTO all_options VALUES (116,1,'I feel much worse off');
INSERT INTO all_options VALUES (116,2,'I feel a little worse off');
INSERT INTO all_options VALUES (116,3,'No different');
INSERT INTO all_options VALUES (116,4,'I feel a little better off');
INSERT INTO all_options VALUES (116,5,'I feel much better off');
INSERT INTO all_options VALUES (117,1,'No, not at all');
INSERT INTO all_options VALUES (117,2,'Yes, a little');
INSERT INTO all_options VALUES (117,3,'Yes, a lot');
INSERT INTO all_options VALUES (118,1,'TV set');
INSERT INTO all_options VALUES (118,2,'PVR/DVR which can record TV programs and allows you to pause or rewind live TV');
INSERT INTO all_options VALUES (118,3,'Device for streaming content to your TV set (e.g. Chromecast, Roku Streaming Stick- but not including video game consoles)');
INSERT INTO all_options VALUES (118,4,'DVD or Blu-ray player (not in a laptop)');
INSERT INTO all_options VALUES (118,5,'Desktop computer');
INSERT INTO all_options VALUES (118,6,'Laptop computer');
INSERT INTO all_options VALUES (118,7,'Smartphone (this is a phone on which you can download apps and access email, the internet etc., e.g. iPhone, Samsung Galaxy)');
INSERT INTO all_options VALUES (118,8,'Tablet (e.g. iPad, Samsung Galaxy Tab, Microsoft Surface Pro etc.)');
INSERT INTO all_options VALUES (118,9,'e-Reader (e.g. Kindle)');
INSERT INTO all_options VALUES (118,10,'Video game console (e.g. Xbox, PS4)');
INSERT INTO all_options VALUES (118,11,'Portable gaming console (e.g. Nintendo Switch, PlayStation Vita etc.)');
INSERT INTO all_options VALUES (118,12,'VR (Virtual Reality) headset (e.g. Google Cardboard, Oculus Rift)');
INSERT INTO all_options VALUES (118,13,'Wireless home speaker systems to play music, TV, or movies (e.g. Bose, Sonos)');
INSERT INTO all_options VALUES (118,14,'Premium headphones that cost $200 or more');
INSERT INTO all_options VALUES (118,15,'Digital radio');
INSERT INTO all_options VALUES (118,16,'Smartwatch (e.g. Samsung Gear, Apple watch)');
INSERT INTO all_options VALUES (118,17,'Fitness tracker (e.g. Fitbit, Garmin)');
INSERT INTO all_options VALUES (118,18,'Smart Home speakers (e.g. Google Home, Amazon Echo)');
INSERT INTO all_options VALUES (118,19,'Voice assistant (virtual assistants that can perform tasks or services based on verbal commands, e.g. Google, Siri, Alexa, Cortana)');
INSERT INTO all_options VALUES (118,20,'Smart home extensions that use technology to control household appliances such as lights, sound systems and thermostats (e.g. NEST, smart heating thermostats, smart lightbulbs etc.)');
INSERT INTO all_options VALUES (118,21,'None of these');
INSERT INTO all_options VALUES (119,1,'Yes');
INSERT INTO all_options VALUES (119,2,'No');
INSERT INTO all_options VALUES (121,1,'I never use this device');
INSERT INTO all_options VALUES (121,2,'Once a week');
INSERT INTO all_options VALUES (121,3,'2-3 times a week');
INSERT INTO all_options VALUES (121,4,'4-5 times a week');
INSERT INTO all_options VALUES (121,5,'Daily');
INSERT INTO all_options VALUES (121,6,'Multiple times every day');
INSERT INTO all_options VALUES (122,1,'I never use this device');
INSERT INTO all_options VALUES (122,2,'Once a week');
INSERT INTO all_options VALUES (122,3,'2-3 times a week');
INSERT INTO all_options VALUES (122,4,'4-5 times a week');
INSERT INTO all_options VALUES (122,5,'Daily');
INSERT INTO all_options VALUES (122,6,'Multiple times every day');
INSERT INTO all_options VALUES (123,1,'I never use this device');
INSERT INTO all_options VALUES (123,2,'Once a week');
INSERT INTO all_options VALUES (123,3,'2-3 times a week');
INSERT INTO all_options VALUES (123,4,'4-5 times a week');
INSERT INTO all_options VALUES (123,5,'Daily');
INSERT INTO all_options VALUES (123,6,'Multiple times every day');
INSERT INTO all_options VALUES (124,1,'I never use this device');
INSERT INTO all_options VALUES (124,2,'Once a week');
INSERT INTO all_options VALUES (124,3,'2-3 times a week');
INSERT INTO all_options VALUES (124,4,'4-5 times a week');
INSERT INTO all_options VALUES (124,5,'Daily');
INSERT INTO all_options VALUES (124,6,'Multiple times every day');
INSERT INTO all_options VALUES (125,1,'I never use this device');
INSERT INTO all_options VALUES (125,2,'Once a week');
INSERT INTO all_options VALUES (125,3,'2-3 times a week');
INSERT INTO all_options VALUES (125,4,'4-5 times a week');
INSERT INTO all_options VALUES (125,5,'Daily');
INSERT INTO all_options VALUES (125,6,'Multiple times every day');
INSERT INTO all_options VALUES (126,1,'I never use this device');
INSERT INTO all_options VALUES (126,2,'Once a week');
INSERT INTO all_options VALUES (126,3,'2-3 times a week');
INSERT INTO all_options VALUES (126,4,'4-5 times a week');
INSERT INTO all_options VALUES (126,5,'Daily');
INSERT INTO all_options VALUES (126,6,'Multiple times every day');
INSERT INTO all_options VALUES (127,1,'I never use this device');
INSERT INTO all_options VALUES (127,2,'Once a week');
INSERT INTO all_options VALUES (127,3,'2-3 times a week');
INSERT INTO all_options VALUES (127,4,'4-5 times a week');
INSERT INTO all_options VALUES (127,5,'Daily');
INSERT INTO all_options VALUES (127,6,'Multiple times every day');
INSERT INTO all_options VALUES (128,1,'I never use this device');
INSERT INTO all_options VALUES (128,2,'Once a week');
INSERT INTO all_options VALUES (128,3,'2-3 times a week');
INSERT INTO all_options VALUES (128,4,'4-5 times a week');
INSERT INTO all_options VALUES (128,5,'Daily');
INSERT INTO all_options VALUES (128,6,'Multiple times every day');
INSERT INTO all_options VALUES (129,1,'I never use this device');
INSERT INTO all_options VALUES (129,2,'Once a week');
INSERT INTO all_options VALUES (129,3,'2-3 times a week');
INSERT INTO all_options VALUES (129,4,'4-5 times a week');
INSERT INTO all_options VALUES (129,5,'Daily');
INSERT INTO all_options VALUES (129,6,'Multiple times every day');
INSERT INTO all_options VALUES (130,1,'I never use this device');
INSERT INTO all_options VALUES (130,2,'Once a week');
INSERT INTO all_options VALUES (130,3,'2-3 times a week');
INSERT INTO all_options VALUES (130,4,'4-5 times a week');
INSERT INTO all_options VALUES (130,5,'Daily');
INSERT INTO all_options VALUES (130,6,'Multiple times every day');
INSERT INTO all_options VALUES (131,1,'I never use this device');
INSERT INTO all_options VALUES (131,2,'Once a week');
INSERT INTO all_options VALUES (131,3,'2-3 times a week');
INSERT INTO all_options VALUES (131,4,'4-5 times a week');
INSERT INTO all_options VALUES (131,5,'Daily');
INSERT INTO all_options VALUES (131,6,'Multiple times every day');
INSERT INTO all_options VALUES (132,1,'I never use this device');
INSERT INTO all_options VALUES (132,2,'Once a week');
INSERT INTO all_options VALUES (132,3,'2-3 times a week');
INSERT INTO all_options VALUES (132,4,'4-5 times a week');
INSERT INTO all_options VALUES (132,5,'Daily');
INSERT INTO all_options VALUES (132,6,'Multiple times every day');
INSERT INTO all_options VALUES (133,1,'I never use this device');
INSERT INTO all_options VALUES (133,2,'Once a week');
INSERT INTO all_options VALUES (133,3,'2-3 times a week');
INSERT INTO all_options VALUES (133,4,'4-5 times a week');
INSERT INTO all_options VALUES (133,5,'Daily');
INSERT INTO all_options VALUES (133,6,'Multiple times every day');
INSERT INTO all_options VALUES (134,1,'I never use this device');
INSERT INTO all_options VALUES (134,2,'Once a week');
INSERT INTO all_options VALUES (134,3,'2-3 times a week');
INSERT INTO all_options VALUES (134,4,'4-5 times a week');
INSERT INTO all_options VALUES (134,5,'Daily');
INSERT INTO all_options VALUES (134,6,'Multiple times every day');
INSERT INTO all_options VALUES (135,1,'I never use this device');
INSERT INTO all_options VALUES (135,2,'Once a week');
INSERT INTO all_options VALUES (135,3,'2-3 times a week');
INSERT INTO all_options VALUES (135,4,'4-5 times a week');
INSERT INTO all_options VALUES (135,5,'Daily');
INSERT INTO all_options VALUES (135,6,'Multiple times every day');
INSERT INTO all_options VALUES (136,1,'I never use this device');
INSERT INTO all_options VALUES (136,2,'Once a week');
INSERT INTO all_options VALUES (136,3,'2-3 times a week');
INSERT INTO all_options VALUES (136,4,'4-5 times a week');
INSERT INTO all_options VALUES (136,5,'Daily');
INSERT INTO all_options VALUES (136,6,'Multiple times every day');
INSERT INTO all_options VALUES (137,1,'I never use this device');
INSERT INTO all_options VALUES (137,2,'Once a week');
INSERT INTO all_options VALUES (137,3,'2-3 times a week');
INSERT INTO all_options VALUES (137,4,'4-5 times a week');
INSERT INTO all_options VALUES (137,5,'Daily');
INSERT INTO all_options VALUES (137,6,'Multiple times every day');
INSERT INTO all_options VALUES (138,1,'I never use this device');
INSERT INTO all_options VALUES (138,2,'Once a week');
INSERT INTO all_options VALUES (138,3,'2-3 times a week');
INSERT INTO all_options VALUES (138,4,'4-5 times a week');
INSERT INTO all_options VALUES (138,5,'Daily');
INSERT INTO all_options VALUES (138,6,'Multiple times every day');
INSERT INTO all_options VALUES (139,1,'I never use this device');
INSERT INTO all_options VALUES (139,2,'Once a week');
INSERT INTO all_options VALUES (139,3,'2-3 times a week');
INSERT INTO all_options VALUES (139,4,'4-5 times a week');
INSERT INTO all_options VALUES (139,5,'Daily');
INSERT INTO all_options VALUES (139,6,'Multiple times every day');
INSERT INTO all_options VALUES (140,1,'I never use this device');
INSERT INTO all_options VALUES (140,2,'Once a week');
INSERT INTO all_options VALUES (140,3,'2-3 times a week');
INSERT INTO all_options VALUES (140,4,'4-5 times a week');
INSERT INTO all_options VALUES (140,5,'Daily');
INSERT INTO all_options VALUES (140,6,'Multiple times every day');
INSERT INTO all_options VALUES (142,1,'I don''t know anything');
INSERT INTO all_options VALUES (142,2,'I don''t know much');
INSERT INTO all_options VALUES (142,3,'I know a little');
INSERT INTO all_options VALUES (142,4,'I know a lot');
INSERT INTO all_options VALUES (143,1,'I don''t know anything');
INSERT INTO all_options VALUES (143,2,'I don''t know much');
INSERT INTO all_options VALUES (143,3,'I know a little');
INSERT INTO all_options VALUES (143,4,'I know a lot');
INSERT INTO all_options VALUES (144,1,'I don''t know anything');
INSERT INTO all_options VALUES (144,2,'I don''t know much');
INSERT INTO all_options VALUES (144,3,'I know a little');
INSERT INTO all_options VALUES (144,4,'I know a lot');
INSERT INTO all_options VALUES (145,1,'I don''t know anything');
INSERT INTO all_options VALUES (145,2,'I don''t know much');
INSERT INTO all_options VALUES (145,3,'I know a little');
INSERT INTO all_options VALUES (145,4,'I know a lot');
INSERT INTO all_options VALUES (146,1,'I don''t know anything');
INSERT INTO all_options VALUES (146,2,'I don''t know much');
INSERT INTO all_options VALUES (146,3,'I know a little');
INSERT INTO all_options VALUES (146,4,'I know a lot');
INSERT INTO all_options VALUES (147,1,'I don''t know anything');
INSERT INTO all_options VALUES (147,2,'I don''t know much');
INSERT INTO all_options VALUES (147,3,'I know a little');
INSERT INTO all_options VALUES (147,4,'I know a lot');
INSERT INTO all_options VALUES (149,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (149,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (149,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (150,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (150,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (150,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (151,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (151,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (151,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (152,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (152,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (152,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (153,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (153,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (153,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (154,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (154,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (154,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (155,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (155,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (155,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (156,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (156,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (156,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (157,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (157,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (157,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (158,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (158,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (158,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (159,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (159,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (159,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (160,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (160,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (160,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (161,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (161,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (161,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (162,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (162,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (162,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (163,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (163,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (163,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (164,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (164,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (164,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (165,1,'I know this to be FALSE');
INSERT INTO all_options VALUES (165,2,'I''m not sure if this is true or false');
INSERT INTO all_options VALUES (165,3,'I know this to be TRUE');
INSERT INTO all_options VALUES (167,1,'Disagree strongly');
INSERT INTO all_options VALUES (167,2,'Disagree somewhat');
INSERT INTO all_options VALUES (167,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (167,4,'Agree somewhat');
INSERT INTO all_options VALUES (167,5,'Agree strongly');
INSERT INTO all_options VALUES (168,1,'Disagree strongly');
INSERT INTO all_options VALUES (168,2,'Disagree somewhat');
INSERT INTO all_options VALUES (168,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (168,4,'Agree somewhat');
INSERT INTO all_options VALUES (168,5,'Agree strongly');
INSERT INTO all_options VALUES (169,1,'Disagree strongly');
INSERT INTO all_options VALUES (169,2,'Disagree somewhat');
INSERT INTO all_options VALUES (169,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (169,4,'Agree somewhat');
INSERT INTO all_options VALUES (169,5,'Agree strongly');
INSERT INTO all_options VALUES (170,1,'Disagree strongly');
INSERT INTO all_options VALUES (170,2,'Disagree somewhat');
INSERT INTO all_options VALUES (170,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (170,4,'Agree somewhat');
INSERT INTO all_options VALUES (170,5,'Agree strongly');
INSERT INTO all_options VALUES (171,1,'Disagree strongly');
INSERT INTO all_options VALUES (171,2,'Disagree somewhat');
INSERT INTO all_options VALUES (171,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (171,4,'Agree somewhat');
INSERT INTO all_options VALUES (171,5,'Agree strongly');
INSERT INTO all_options VALUES (172,1,'Disagree strongly');
INSERT INTO all_options VALUES (172,2,'Disagree somewhat');
INSERT INTO all_options VALUES (172,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (172,4,'Agree somewhat');
INSERT INTO all_options VALUES (172,5,'Agree strongly');
INSERT INTO all_options VALUES (173,1,'Disagree strongly');
INSERT INTO all_options VALUES (173,2,'Disagree somewhat');
INSERT INTO all_options VALUES (173,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (173,4,'Agree somewhat');
INSERT INTO all_options VALUES (173,5,'Agree strongly');
INSERT INTO all_options VALUES (174,1,'Disagree strongly');
INSERT INTO all_options VALUES (174,2,'Disagree somewhat');
INSERT INTO all_options VALUES (174,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (174,4,'Agree somewhat');
INSERT INTO all_options VALUES (174,5,'Agree strongly');
INSERT INTO all_options VALUES (175,1,'Disagree strongly');
INSERT INTO all_options VALUES (175,2,'Disagree somewhat');
INSERT INTO all_options VALUES (175,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (175,4,'Agree somewhat');
INSERT INTO all_options VALUES (175,5,'Agree strongly');
INSERT INTO all_options VALUES (176,1,'Disagree strongly');
INSERT INTO all_options VALUES (176,2,'Disagree somewhat');
INSERT INTO all_options VALUES (176,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (176,4,'Agree somewhat');
INSERT INTO all_options VALUES (176,5,'Agree strongly');
INSERT INTO all_options VALUES (177,1,'Disagree strongly');
INSERT INTO all_options VALUES (177,2,'Disagree somewhat');
INSERT INTO all_options VALUES (177,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (177,4,'Agree somewhat');
INSERT INTO all_options VALUES (177,5,'Agree strongly');
INSERT INTO all_options VALUES (178,1,'Disagree strongly');
INSERT INTO all_options VALUES (178,2,'Disagree somewhat');
INSERT INTO all_options VALUES (178,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (178,4,'Agree somewhat');
INSERT INTO all_options VALUES (178,5,'Agree strongly');
INSERT INTO all_options VALUES (179,1,'Disagree strongly');
INSERT INTO all_options VALUES (179,2,'Disagree somewhat');
INSERT INTO all_options VALUES (179,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (179,4,'Agree somewhat');
INSERT INTO all_options VALUES (179,5,'Agree strongly');
INSERT INTO all_options VALUES (180,1,'Disagree strongly');
INSERT INTO all_options VALUES (180,2,'Disagree somewhat');
INSERT INTO all_options VALUES (180,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (180,4,'Agree somewhat');
INSERT INTO all_options VALUES (180,5,'Agree strongly');
INSERT INTO all_options VALUES (181,1,'Disagree strongly');
INSERT INTO all_options VALUES (181,2,'Disagree somewhat');
INSERT INTO all_options VALUES (181,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (181,4,'Agree somewhat');
INSERT INTO all_options VALUES (181,5,'Agree strongly');
INSERT INTO all_options VALUES (182,1,'Disagree strongly');
INSERT INTO all_options VALUES (182,2,'Disagree somewhat');
INSERT INTO all_options VALUES (182,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (182,4,'Agree somewhat');
INSERT INTO all_options VALUES (182,5,'Agree strongly');
INSERT INTO all_options VALUES (183,1,'Disagree strongly');
INSERT INTO all_options VALUES (183,2,'Disagree somewhat');
INSERT INTO all_options VALUES (183,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (183,4,'Agree somewhat');
INSERT INTO all_options VALUES (183,5,'Agree strongly');
INSERT INTO all_options VALUES (184,1,'Disagree strongly');
INSERT INTO all_options VALUES (184,2,'Disagree somewhat');
INSERT INTO all_options VALUES (184,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (184,4,'Agree somewhat');
INSERT INTO all_options VALUES (184,5,'Agree strongly');
INSERT INTO all_options VALUES (185,1,'Disagree strongly');
INSERT INTO all_options VALUES (185,2,'Disagree somewhat');
INSERT INTO all_options VALUES (185,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (185,4,'Agree somewhat');
INSERT INTO all_options VALUES (185,5,'Agree strongly');
INSERT INTO all_options VALUES (186,1,'Disagree strongly');
INSERT INTO all_options VALUES (186,2,'Disagree somewhat');
INSERT INTO all_options VALUES (186,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (186,4,'Agree somewhat');
INSERT INTO all_options VALUES (186,5,'Agree strongly');
INSERT INTO all_options VALUES (188,1,'Disagree strongly');
INSERT INTO all_options VALUES (188,2,'Disagree somewhat');
INSERT INTO all_options VALUES (188,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (188,4,'Agree somewhat');
INSERT INTO all_options VALUES (188,5,'Agree strongly');
INSERT INTO all_options VALUES (189,1,'Disagree strongly');
INSERT INTO all_options VALUES (189,2,'Disagree somewhat');
INSERT INTO all_options VALUES (189,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (189,4,'Agree somewhat');
INSERT INTO all_options VALUES (189,5,'Agree strongly');
INSERT INTO all_options VALUES (190,1,'Disagree strongly');
INSERT INTO all_options VALUES (190,2,'Disagree somewhat');
INSERT INTO all_options VALUES (190,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (190,4,'Agree somewhat');
INSERT INTO all_options VALUES (190,5,'Agree strongly');
INSERT INTO all_options VALUES (191,1,'Disagree strongly');
INSERT INTO all_options VALUES (191,2,'Disagree somewhat');
INSERT INTO all_options VALUES (191,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (191,4,'Agree somewhat');
INSERT INTO all_options VALUES (191,5,'Agree strongly');
INSERT INTO all_options VALUES (192,1,'Disagree strongly');
INSERT INTO all_options VALUES (192,2,'Disagree somewhat');
INSERT INTO all_options VALUES (192,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (192,4,'Agree somewhat');
INSERT INTO all_options VALUES (192,5,'Agree strongly');
INSERT INTO all_options VALUES (193,1,'Disagree strongly');
INSERT INTO all_options VALUES (193,2,'Disagree somewhat');
INSERT INTO all_options VALUES (193,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (193,4,'Agree somewhat');
INSERT INTO all_options VALUES (193,5,'Agree strongly');
INSERT INTO all_options VALUES (194,1,'Disagree strongly');
INSERT INTO all_options VALUES (194,2,'Disagree somewhat');
INSERT INTO all_options VALUES (194,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (194,4,'Agree somewhat');
INSERT INTO all_options VALUES (194,5,'Agree strongly');
INSERT INTO all_options VALUES (195,1,'Disagree strongly');
INSERT INTO all_options VALUES (195,2,'Disagree somewhat');
INSERT INTO all_options VALUES (195,3,'Neither agree not disagree');
INSERT INTO all_options VALUES (195,4,'Agree somewhat');
INSERT INTO all_options VALUES (195,5,'Agree strongly');
INSERT INTO all_options VALUES (197,1,'1');
INSERT INTO all_options VALUES (197,2,'2');
INSERT INTO all_options VALUES (197,3,'3');
INSERT INTO all_options VALUES (197,4,'4');
INSERT INTO all_options VALUES (197,5,'5');
INSERT INTO all_options VALUES (198,1,'1');
INSERT INTO all_options VALUES (198,2,'2');
INSERT INTO all_options VALUES (198,3,'3');
INSERT INTO all_options VALUES (198,4,'4');
INSERT INTO all_options VALUES (198,5,'5');
INSERT INTO all_options VALUES (199,1,'1');
INSERT INTO all_options VALUES (199,2,'2');
INSERT INTO all_options VALUES (199,3,'3');
INSERT INTO all_options VALUES (199,4,'4');
INSERT INTO all_options VALUES (199,5,'5');
INSERT INTO all_options VALUES (200,1,'1');
INSERT INTO all_options VALUES (200,2,'2');
INSERT INTO all_options VALUES (200,3,'3');
INSERT INTO all_options VALUES (200,4,'4');
INSERT INTO all_options VALUES (200,5,'5');
INSERT INTO all_options VALUES (201,1,'1');
INSERT INTO all_options VALUES (201,2,'2');
INSERT INTO all_options VALUES (201,3,'3');
INSERT INTO all_options VALUES (201,4,'4');
INSERT INTO all_options VALUES (201,5,'5');
INSERT INTO all_options VALUES (202,1,'1');
INSERT INTO all_options VALUES (202,2,'2');
INSERT INTO all_options VALUES (202,3,'3');
INSERT INTO all_options VALUES (202,4,'4');
INSERT INTO all_options VALUES (202,5,'5');
INSERT INTO all_options VALUES (204,1,'Disagree completely');
INSERT INTO all_options VALUES (204,2,'Disagree somewhat');
INSERT INTO all_options VALUES (204,3,'Agree somewhat');
INSERT INTO all_options VALUES (204,4,'Agree completely');
INSERT INTO all_options VALUES (205,1,'Disagree completely');
INSERT INTO all_options VALUES (205,2,'Disagree somewhat');
INSERT INTO all_options VALUES (205,3,'Agree somewhat');
INSERT INTO all_options VALUES (205,4,'Agree completely');
INSERT INTO all_options VALUES (206,1,'Disagree completely');
INSERT INTO all_options VALUES (206,2,'Disagree somewhat');
INSERT INTO all_options VALUES (206,3,'Agree somewhat');
INSERT INTO all_options VALUES (206,4,'Agree completely');
INSERT INTO all_options VALUES (207,1,'Disagree completely');
INSERT INTO all_options VALUES (207,2,'Disagree somewhat');
INSERT INTO all_options VALUES (207,3,'Agree somewhat');
INSERT INTO all_options VALUES (207,4,'Agree completely');
INSERT INTO all_options VALUES (208,1,'Disagree completely');
INSERT INTO all_options VALUES (208,2,'Disagree somewhat');
INSERT INTO all_options VALUES (208,3,'Agree somewhat');
INSERT INTO all_options VALUES (208,4,'Agree completely');
INSERT INTO all_options VALUES (209,1,'Disagree completely');
INSERT INTO all_options VALUES (209,2,'Disagree somewhat');
INSERT INTO all_options VALUES (209,3,'Agree somewhat');
INSERT INTO all_options VALUES (209,4,'Agree completely');
INSERT INTO all_options VALUES (210,1,'Disagree completely');
INSERT INTO all_options VALUES (210,2,'Disagree somewhat');
INSERT INTO all_options VALUES (210,3,'Agree somewhat');
INSERT INTO all_options VALUES (210,4,'Agree completely');
INSERT INTO all_options VALUES (211,1,'Disagree completely');
INSERT INTO all_options VALUES (211,2,'Disagree somewhat');
INSERT INTO all_options VALUES (211,3,'Agree somewhat');
INSERT INTO all_options VALUES (211,4,'Agree completely');
INSERT INTO all_options VALUES (212,1,'Disagree completely');
INSERT INTO all_options VALUES (212,2,'Disagree somewhat');
INSERT INTO all_options VALUES (212,3,'Agree somewhat');
INSERT INTO all_options VALUES (212,4,'Agree completely');
INSERT INTO all_options VALUES (213,1,'Disagree completely');
INSERT INTO all_options VALUES (213,2,'Disagree somewhat');
INSERT INTO all_options VALUES (213,3,'Agree somewhat');
INSERT INTO all_options VALUES (213,4,'Agree completely');
INSERT INTO all_options VALUES (215,1,'Alone');
INSERT INTO all_options VALUES (215,2,'My partner');
INSERT INTO all_options VALUES (215,3,'My child(ren)');
INSERT INTO all_options VALUES (215,4,'My parent(s)');
INSERT INTO all_options VALUES (215,5,'My bother(s)/sister(s)/ aged 15 or younger');
INSERT INTO all_options VALUES (215,6,'My bother(s)/sister(s)/ aged 16 or older');
INSERT INTO all_options VALUES (215,7,'Friend(s)');
INSERT INTO all_options VALUES (215,8,'Others');
INSERT INTO all_options VALUES (216,1,'No, no long term health issues');
INSERT INTO all_options VALUES (216,2,'Asthma or respiratory problems');
INSERT INTO all_options VALUES (216,3,'Chronic pain');
INSERT INTO all_options VALUES (216,4,'Heart or cardiovascular issues');
INSERT INTO all_options VALUES (216,5,'Cancer');
INSERT INTO all_options VALUES (216,6,'Auto-immune disease');
INSERT INTO all_options VALUES (216,7,'Kidney disease');
INSERT INTO all_options VALUES (216,8,'Diabetes');
INSERT INTO all_options VALUES (216,9,'Liver disease');
INSERT INTO all_options VALUES (216,10,'Other serious illness');
INSERT INTO all_options VALUES (217,1,'0-4 years old');
INSERT INTO all_options VALUES (217,2,'5-10 years old');
INSERT INTO all_options VALUES (217,3,'11-14 years old');
INSERT INTO all_options VALUES (217,4,'15-18 years old');
INSERT INTO all_options VALUES (218,1,'No, not at all');
INSERT INTO all_options VALUES (218,2,'Yes, a little, but they''re still in school');
INSERT INTO all_options VALUES (218,3,'Yes, a lot, they''re not going to school');
INSERT INTO all_options VALUES (219,1,'No, no long term health issues');
INSERT INTO all_options VALUES (219,2,'Asthma or respiratory problems');
INSERT INTO all_options VALUES (219,3,'Chronic pain');
INSERT INTO all_options VALUES (219,4,'Heart or cardiovascular issues');
INSERT INTO all_options VALUES (219,5,'Cancer');
INSERT INTO all_options VALUES (219,6,'Auto-immune disease');
INSERT INTO all_options VALUES (219,7,'Kidney disease');
INSERT INTO all_options VALUES (219,8,'Diabetes');
INSERT INTO all_options VALUES (219,9,'Liver disease');
INSERT INTO all_options VALUES (219,10,'Other serious illness');
INSERT INTO all_options VALUES (220,1,'Very senior management in business or commerce');
INSERT INTO all_options VALUES (220,2,'Principal officer in local government or civil service');
INSERT INTO all_options VALUES (220,3,'Top level civil servant');
INSERT INTO all_options VALUES (220,4,'Professional, e.g. lawyer, accountant, doctor');
INSERT INTO all_options VALUES (220,5,'Public service (police, health, education, fire service)');
INSERT INTO all_options VALUES (220,6,'Middle management executive in large organisation');
INSERT INTO all_options VALUES (220,7,'Junior management');
INSERT INTO all_options VALUES (220,8,'Non-manual worker e.g. clerical, secretarial or sales');
INSERT INTO all_options VALUES (220,9,'Skilled manual worker with responsibility for other people');
INSERT INTO all_options VALUES (220,10,'Manual worker with responsibility for other people');
INSERT INTO all_options VALUES (220,11,'Semi-skilled manual worker e.g. security guard, catering staff');
INSERT INTO all_options VALUES (220,12,'Apprentice or trainee to skilled workers');
INSERT INTO all_options VALUES (220,13,'In full time education');
INSERT INTO all_options VALUES (220,14,'Unemployed');
INSERT INTO all_options VALUES (220,15,'Other');
INSERT INTO all_options VALUES (221,1,'ABC1');
INSERT INTO all_options VALUES (221,2,'C2DE');
INSERT INTO all_options VALUES (222,1,'A few years of secondary education or less');
INSERT INTO all_options VALUES (222,2,'Completed secondary education');
INSERT INTO all_options VALUES (222,3,'University degree');
INSERT INTO all_options VALUES (222,4,'Masters, doctorate or above');
INSERT INTO all_options VALUES (222,5,'Prefer not to answer');
INSERT INTO all_options VALUES (223,1,'City centre');
INSERT INTO all_options VALUES (223,2,'Suburbs');
INSERT INTO all_options VALUES (223,3,'Large town');
INSERT INTO all_options VALUES (223,4,'Small town or village');
INSERT INTO all_options VALUES (223,5,'Rural');
INSERT INTO all_options VALUES (224,1,'Urban');
INSERT INTO all_options VALUES (224,2,'Rural');
INSERT INTO all_options VALUES (225,1,'North East England');
INSERT INTO all_options VALUES (225,2,'North West England');
INSERT INTO all_options VALUES (225,3,'Yorkshire & Humberside');
INSERT INTO all_options VALUES (225,4,'East Midlands');
INSERT INTO all_options VALUES (225,5,'West Midlands');
INSERT INTO all_options VALUES (225,6,'East Anglia');
INSERT INTO all_options VALUES (225,7,'South East England');
INSERT INTO all_options VALUES (225,8,'South West England');
INSERT INTO all_options VALUES (225,9,'London');
INSERT INTO all_options VALUES (225,10,'Northern Ireland');
INSERT INTO all_options VALUES (225,11,'Scotland');
INSERT INTO all_options VALUES (225,12,'Wales');
INSERT INTO all_options VALUES (226,1,'Less than GBP 15,000');
INSERT INTO all_options VALUES (226,2,'GBP 15,000 - 25,000');
INSERT INTO all_options VALUES (226,3,'GBP 25,001 - 35,000');
INSERT INTO all_options VALUES (226,4,'GBP 35,001 - 50,000');
INSERT INTO all_options VALUES (226,5,'GBP 50,001 - 75,000');
INSERT INTO all_options VALUES (226,6,'GBP 75,001 - 100,000');
INSERT INTO all_options VALUES (226,7,'Over GBP 100,000');
INSERT INTO all_options VALUES (226,8,'Prefer not to answer');
INSERT INTO all_options VALUES (227,1,'White');
INSERT INTO all_options VALUES (227,2,'Mixed/multiple ethnic groups');
INSERT INTO all_options VALUES (227,3,'Asian or British Asian');
INSERT INTO all_options VALUES (227,4,'Black/African/Caribbean/Black British');
INSERT INTO all_options VALUES (227,5,'Other ethnic group');
INSERT INTO all_options VALUES (227,6,'Prefer not to answer');
INSERT INTO all_options VALUES (228,1,'Alabama');
INSERT INTO all_options VALUES (228,2,'Alaska');
INSERT INTO all_options VALUES (228,3,'Arizona');
INSERT INTO all_options VALUES (228,4,'Arkansas');
INSERT INTO all_options VALUES (228,5,'California');
INSERT INTO all_options VALUES (228,6,'Colorado');
INSERT INTO all_options VALUES (228,7,'Connecticut');
INSERT INTO all_options VALUES (228,8,'Delaware');
INSERT INTO all_options VALUES (228,9,'District of Columbia (D.C.)');
INSERT INTO all_options VALUES (228,10,'Florida');
INSERT INTO all_options VALUES (228,11,'Georgia');
INSERT INTO all_options VALUES (228,12,'Hawaii');
INSERT INTO all_options VALUES (228,13,'Idaho');
INSERT INTO all_options VALUES (228,14,'Illinois');
INSERT INTO all_options VALUES (228,15,'Indiana');
INSERT INTO all_options VALUES (228,16,'Iowa');
INSERT INTO all_options VALUES (228,17,'Kansas');
INSERT INTO all_options VALUES (228,18,'Kentucky');
INSERT INTO all_options VALUES (228,19,'Louisiana');
INSERT INTO all_options VALUES (228,20,'Maine');
INSERT INTO all_options VALUES (228,21,'Maryland');
INSERT INTO all_options VALUES (228,22,'Massachusetts');
INSERT INTO all_options VALUES (228,23,'Michigan');
INSERT INTO all_options VALUES (228,24,'Minnesota');
INSERT INTO all_options VALUES (228,25,'Mississippi');
INSERT INTO all_options VALUES (228,26,'Missouri');
INSERT INTO all_options VALUES (228,27,'Montana');
INSERT INTO all_options VALUES (228,28,'Nebraska');
INSERT INTO all_options VALUES (228,29,'Nevada');
INSERT INTO all_options VALUES (228,30,'New Hampshire');
INSERT INTO all_options VALUES (228,31,'New Jersey');
INSERT INTO all_options VALUES (228,32,'New Mexico');
INSERT INTO all_options VALUES (228,33,'New York');
INSERT INTO all_options VALUES (228,34,'North Carolina');
INSERT INTO all_options VALUES (228,35,'North Dakota');
INSERT INTO all_options VALUES (228,36,'Ohio');
INSERT INTO all_options VALUES (228,37,'Oklahoma');
INSERT INTO all_options VALUES (228,38,'Oregon');
INSERT INTO all_options VALUES (228,39,'Pennsylvania');
INSERT INTO all_options VALUES (228,40,'Rhode Island');
INSERT INTO all_options VALUES (228,41,'South Carolina');
INSERT INTO all_options VALUES (228,42,'South Dakota');
INSERT INTO all_options VALUES (228,43,'Tennessee');
INSERT INTO all_options VALUES (228,44,'Texas');
INSERT INTO all_options VALUES (228,45,'Utah');
INSERT INTO all_options VALUES (228,46,'Vermont');
INSERT INTO all_options VALUES (228,47,'Virginia');
INSERT INTO all_options VALUES (228,48,'Washington');
INSERT INTO all_options VALUES (228,49,'West Virginia');
INSERT INTO all_options VALUES (228,50,'Wisconsin');
INSERT INTO all_options VALUES (228,51,'Wyoming');
INSERT INTO all_options VALUES (229,1,'New England (Connecticut, Maine, Massachusetts, New Hampshire, Rhode Island, and Vermont)');
INSERT INTO all_options VALUES (229,2,'Mid-Atlantic (Delaware, District of Columbia, New Jersey, New York, Maryland, Pennsylvania and West Virginia)');
INSERT INTO all_options VALUES (229,3,'East North Central (Illinois, Indiana, Michigan, Ohio, and Wisconsin)');
INSERT INTO all_options VALUES (229,4,'West North Central (Iowa, Kansas, Minnesota, Missouri, Nebraska, North Dakota, and South Dakota)');
INSERT INTO all_options VALUES (229,5,'South Atlantic (Florida, Georgia, North Carolina, South Carolina, and Virginia)');
INSERT INTO all_options VALUES (229,6,'East South Central (Alabama, Kentucky, Mississippi, and Tennessee)');
INSERT INTO all_options VALUES (229,7,'West South Central (Arkansas, Louisiana, Oklahoma, and Texas)');
INSERT INTO all_options VALUES (229,8,'Mountain (Arizona, Colorado, Idaho, Montana, Nevada, New Mexico, Utah, and Wyoming)');
INSERT INTO all_options VALUES (229,9,'Pacific (Alaska, California, Hawaii, Oregon, and Washington)');
INSERT INTO all_options VALUES (230,1,'Less than $ 20,000');
INSERT INTO all_options VALUES (230,2,'$ 20,000 - $ 29,999');
INSERT INTO all_options VALUES (230,3,'$ 30,000 - $ 39,999');
INSERT INTO all_options VALUES (230,4,'$ 40,000 - $ 49,999');
INSERT INTO all_options VALUES (230,5,'$ 50,000 - $ 59,999');
INSERT INTO all_options VALUES (230,6,'$ 60,000 - $ 74,999');
INSERT INTO all_options VALUES (230,7,'$ 75,000 - $ 99,999');
INSERT INTO all_options VALUES (230,8,'$ 100,000 - $ 149,999');
INSERT INTO all_options VALUES (230,9,'$ 150,000 +');
INSERT INTO all_options VALUES (230,10,'Prefer not to answer');
INSERT INTO all_options VALUES (231,1,'White or Caucasian (not Hispanic or Latino)');
INSERT INTO all_options VALUES (231,2,'Black or African-American (not Hispanic or Latino)');
INSERT INTO all_options VALUES (231,3,'Asian/Pacific Islander');
INSERT INTO all_options VALUES (231,4,'Native American, Alaska Native, Aleutian');
INSERT INTO all_options VALUES (231,5,'Hispanic or Latino (White or Caucasian)');
INSERT INTO all_options VALUES (231,6,'Hispanic or Latino (Black or African-American)');
INSERT INTO all_options VALUES (231,7,'Hispanic or Latino (all other races/ multiple races)');
INSERT INTO all_options VALUES (231,8,'Other ethnic background');
INSERT INTO all_options VALUES (231,9,'Prefer not to answer');
INSERT INTO all_options VALUES (232,1,'White');
INSERT INTO all_options VALUES (232,2,'Black or African-American');
INSERT INTO all_options VALUES (232,3,'Hispanic');
INSERT INTO all_options VALUES (232,4,'Other');
SELECT * FROM all_options;