DROP TABLE IF EXISTS all_questions;
CREATE TABLE all_questions(
	QuestionID INT,
	QuestionText VARCHAR(255),
	GroupName VARCHAR(255),
	isClosed BOOLEAN
);
INSERT INTO all_questions VALUES (1,'Country','NULL',True);
INSERT INTO all_questions VALUES (2,'Gender','NULL',True);
INSERT INTO all_questions VALUES (3,'Age','NULL',False);
INSERT INTO all_questions VALUES (4,'Age Coded','NULL',True);
INSERT INTO all_questions VALUES (5,'Parent','NULL',True);
INSERT INTO all_questions VALUES (6,'Parental Status Coded','NULL',True);
INSERT INTO all_questions VALUES (7,'Employment','NULL',True);
INSERT INTO all_questions VALUES (8,'Employment Status Coded','NULL',True);
INSERT INTO all_questions VALUES (9,'News','NULL',True);
INSERT INTO all_questions VALUES (10,'Self Then','NULL',False);
INSERT INTO all_questions VALUES (11,'Optimistic about my own future','Self Then',True);
INSERT INTO all_questions VALUES (12,'Optimistic about the future of the world','Self Then',True);
INSERT INTO all_questions VALUES (13,'Happy with my life','Self Then',True);
INSERT INTO all_questions VALUES (14,'World Issues','NULL',False);
INSERT INTO all_questions VALUES (15,'The environment','World Issues',True);
INSERT INTO all_questions VALUES (16,'The global economy','World Issues',True);
INSERT INTO all_questions VALUES (17,'The economy','World Issues',True);
INSERT INTO all_questions VALUES (18,'The healthcare system','World Issues',True);
INSERT INTO all_questions VALUES (19,'The physical health of you and your family','World Issues',True);
INSERT INTO all_questions VALUES (20,'The mental health of you and your family','World Issues',True);
INSERT INTO all_questions VALUES (21,'Work/job prospects','World Issues',True);
INSERT INTO all_questions VALUES (22,'My personal finances','World Issues',True);
INSERT INTO all_questions VALUES (23,'The education system','World Issues',True);
INSERT INTO all_questions VALUES (24,'Politics','World Issues',True);
INSERT INTO all_questions VALUES (25,'How we get along as a society','World Issues',True);
INSERT INTO all_questions VALUES (26,'Interest One','NULL',True);
INSERT INTO all_questions VALUES (27,'Interest Two','NULL',True);
INSERT INTO all_questions VALUES (28,'Current State','NULL',False);
INSERT INTO all_questions VALUES (29,'The environment','Current State',True);
INSERT INTO all_questions VALUES (30,'The global economy','Current State',True);
INSERT INTO all_questions VALUES (31,'The economy','Current State',True);
INSERT INTO all_questions VALUES (32,'The healthcare system','Current State',True);
INSERT INTO all_questions VALUES (33,'The physical health of you and your family','Current State',True);
INSERT INTO all_questions VALUES (34,'The mental health of you and your family','Current State',True);
INSERT INTO all_questions VALUES (35,'Work/job prospects','Current State',True);
INSERT INTO all_questions VALUES (36,'My personal finances','Current State',True);
INSERT INTO all_questions VALUES (37,'The education system','Current State',True);
INSERT INTO all_questions VALUES (38,'Politics','Current State',True);
INSERT INTO all_questions VALUES (39,'How we get along as a society','Current State',True);
INSERT INTO all_questions VALUES (40,'How serious coronavirus','NULL',True);
INSERT INTO all_questions VALUES (41,'When serious','NULL',True);
INSERT INTO all_questions VALUES (42,'Self Now','NULL',False);
INSERT INTO all_questions VALUES (43,'Optimistic about my own future','Self Now',True);
INSERT INTO all_questions VALUES (44,'Optimistic about the future of the world','Self Now',True);
INSERT INTO all_questions VALUES (45,'Happy with my life','Self Now',True);
INSERT INTO all_questions VALUES (46,'Not worried about catching coronavirus','Self Now',True);
INSERT INTO all_questions VALUES (47,'Not worried about family and friends catching coronavirus','Self Now',True);
INSERT INTO all_questions VALUES (48,'Coronavirus is having no impact on my life','Self Now',True);
INSERT INTO all_questions VALUES (49,'Coronavirus has brought out the best of humanity','Self Now',True);
INSERT INTO all_questions VALUES (50,'My family is not worried','Self Now',True);
INSERT INTO all_questions VALUES (51,'Covid-19 Concern','NULL',False);
INSERT INTO all_questions VALUES (52,'The situation will get worse before it gets better','Covid-19 Concern',True);
INSERT INTO all_questions VALUES (53,'Other people should take this more seriously','Covid-19 Concern',True);
INSERT INTO all_questions VALUES (54,'Everyone is over-reacting','Covid-19 Concern',True);
INSERT INTO all_questions VALUES (55,'I don''t understand why my life is on hold','Covid-19 Concern',True);
INSERT INTO all_questions VALUES (56,'I''m more worried about the impact on the economy than the actual virus','Covid-19 Concern',True);
INSERT INTO all_questions VALUES (57,'We''re coming out of the worst of it now','Covid-19 Concern',True);
INSERT INTO all_questions VALUES (58,'I have become more focused on what is important','Covid-19 Concern',True);
INSERT INTO all_questions VALUES (59,'I''m enjoying finding new ways of doing things','Covid-19 Concern',True);
INSERT INTO all_questions VALUES (60,'I understand the need to take precautionary measures','Covid-19 Concern',True);
INSERT INTO all_questions VALUES (61,'The environment will be positively affected by coronavirus measures','Covid-19 Concern',True);
INSERT INTO all_questions VALUES (62,'Confidence Level','NULL',False);
INSERT INTO all_questions VALUES (63,'The healthcare system will get through this relatively unscathed','Confidence Level',True);
INSERT INTO all_questions VALUES (64,'This won''t cause us long term economic issues','Confidence Level',True);
INSERT INTO all_questions VALUES (65,'The government guiding us through this','Confidence Level',True);
INSERT INTO all_questions VALUES (66,'We''ll return to normal everyday life after it passes','Confidence Level',True);
INSERT INTO all_questions VALUES (67,'This will have a positive impact on the environment','Confidence Level',True);
INSERT INTO all_questions VALUES (68,'Lessons for Future','NULL',True);
INSERT INTO all_questions VALUES (69,'Improvements for Future','NULL',True);
INSERT INTO all_questions VALUES (70,'Actions during Covid-19','NULL',False);
INSERT INTO all_questions VALUES (71,'I''m out and about as usual','Actions during Covid-19',True);
INSERT INTO all_questions VALUES (72,'I''m taking no precautions','Actions during Covid-19',True);
INSERT INTO all_questions VALUES (73,'I''ve not cancelled any future plans','Actions during Covid-19',True);
INSERT INTO all_questions VALUES (74,'I''m partaking in more hobbies / interests','Actions during Covid-19',True);
INSERT INTO all_questions VALUES (75,'I''m exercising less now','Actions during Covid-19',True);
INSERT INTO all_questions VALUES (76,'I''m following coronavirus (Covid-19) closely in the news','Actions during Covid-19',True);
INSERT INTO all_questions VALUES (77,'I have to remind my family a lot to take precautions','Actions during Covid-19',True);
INSERT INTO all_questions VALUES (78,'Prevention Measures','NULL',True);
INSERT INTO all_questions VALUES (79,'Behaviour Change One','NULL',False);
INSERT INTO all_questions VALUES (80,'Exercising or playing sports','Behaviour Change One',True);
INSERT INTO all_questions VALUES (81,'Yoga / meditation','Behaviour Change One',True);
INSERT INTO all_questions VALUES (82,'Gaming (console or mobile)','Behaviour Change One',True);
INSERT INTO all_questions VALUES (83,'Board games and jigsaws','Behaviour Change One',True);
INSERT INTO all_questions VALUES (84,'Arts and crafts','Behaviour Change One',True);
INSERT INTO all_questions VALUES (85,'Going to concerts or gigs','Behaviour Change One',True);
INSERT INTO all_questions VALUES (86,'Going to cultural events (e.g. theatre, museums etc.)','Behaviour Change One',True);
INSERT INTO all_questions VALUES (87,'Volunteering with a charity','Behaviour Change One',True);
INSERT INTO all_questions VALUES (88,'Dining out in restaurants','Behaviour Change One',True);
INSERT INTO all_questions VALUES (89,'Eating take away food','Behaviour Change One',True);
INSERT INTO all_questions VALUES (90,'Catching up with friends/family','Behaviour Change One',True);
INSERT INTO all_questions VALUES (91,'Reading books','Behaviour Change One',True);
INSERT INTO all_questions VALUES (92,'Watching TV shows/films','Behaviour Change One',True);
INSERT INTO all_questions VALUES (93,'Internet shopping','Behaviour Change One',True);
INSERT INTO all_questions VALUES (94,'Listening to music','Behaviour Change One',True);
INSERT INTO all_questions VALUES (95,'Listening to podcasts','Behaviour Change One',True);
INSERT INTO all_questions VALUES (96,'Video calls with friends/family','Behaviour Change One',True);
INSERT INTO all_questions VALUES (97,'Online exercise classes','Behaviour Change One',True);
INSERT INTO all_questions VALUES (98,'Watch online theatre/plays','Behaviour Change One',True);
INSERT INTO all_questions VALUES (99,'Watch online gigs/concerts','Behaviour Change One',True);
INSERT INTO all_questions VALUES (100,'Play games online with friends','Behaviour Change One',True);
INSERT INTO all_questions VALUES (101,'Online video gaming','Behaviour Change One',True);
INSERT INTO all_questions VALUES (102,'Online quizzes','Behaviour Change One',True);
INSERT INTO all_questions VALUES (103,'Watching online videos','Behaviour Change One',True);
INSERT INTO all_questions VALUES (104,'Streaming films','Behaviour Change One',True);
INSERT INTO all_questions VALUES (105,'Behaviour Change Two','NULL',True);
INSERT INTO all_questions VALUES (106,'Buying behaviour One','NULL',True);
INSERT INTO all_questions VALUES (107,'Buying behaviour Two','NULL',False);
INSERT INTO all_questions VALUES (108,'Bulk buying food items to stock up','Buying behaviour Two',True);
INSERT INTO all_questions VALUES (109,'Bulk buying non-food items to stock up','Buying behaviour Two',True);
INSERT INTO all_questions VALUES (110,'Getting food deliveries from online retailers','Buying behaviour Two',True);
INSERT INTO all_questions VALUES (111,'Signing up to food delivery subscription services','Buying behaviour Two',True);
INSERT INTO all_questions VALUES (112,'Going to the supermarket','Buying behaviour Two',True);
INSERT INTO all_questions VALUES (113,'Going to the local ''corner'' shop','Buying behaviour Two',True);
INSERT INTO all_questions VALUES (114,'Ordering non-food items from online retailers (e.g. Amazon)','Buying behaviour Two',True);
INSERT INTO all_questions VALUES (115,'Ordering takeaways / deliveries from local restaurants','Buying behaviour Two',True);
INSERT INTO all_questions VALUES (116,'Financial Change','NULL',True);
INSERT INTO all_questions VALUES (117,'Financial Change Cause','NULL',True);
INSERT INTO all_questions VALUES (118,'Household Devices','NULL',True);
INSERT INTO all_questions VALUES (119,'Suspicious','NULL',True);
INSERT INTO all_questions VALUES (120,'Device Usage','NULL',False);
INSERT INTO all_questions VALUES (121,'TV set','Device Usage',True);
INSERT INTO all_questions VALUES (122,'PVR/DVR which can record TV programs and allows you to pause or rewind live TV','Device Usage',True);
INSERT INTO all_questions VALUES (123,'Device for streaming content to your TV set (e.g. Chromecast, Roku Streaming Stick- but not including video game consoles)','Device Usage',True);
INSERT INTO all_questions VALUES (124,'DVD or Blu-ray player (not in a laptop)','Device Usage',True);
INSERT INTO all_questions VALUES (125,'Desktop computer','Device Usage',True);
INSERT INTO all_questions VALUES (126,'Laptop computer','Device Usage',True);
INSERT INTO all_questions VALUES (127,'Smartphone (this is a phone on which you can download apps and access email, the internet etc., e.g. iPhone, Samsung Galaxy)','Device Usage',True);
INSERT INTO all_questions VALUES (128,'Tablet (e.g. iPad, Samsung Galaxy Tab, Microsoft Surface Pro etc.)','Device Usage',True);
INSERT INTO all_questions VALUES (129,'e-Reader (e.g. Kindle)','Device Usage',True);
INSERT INTO all_questions VALUES (130,'Video game console (e.g. Xbox, PS4)','Device Usage',True);
INSERT INTO all_questions VALUES (131,'Portable gaming console (e.g. Nintendo Switch, PlayStation Vita etc.)','Device Usage',True);
INSERT INTO all_questions VALUES (132,'VR (Virtual Reality) headset (e.g. Google Cardboard, Oculus Rift)','Device Usage',True);
INSERT INTO all_questions VALUES (133,'Wireless home speaker systems to play music, TV, or movies (e.g. Bose, Sonos)','Device Usage',True);
INSERT INTO all_questions VALUES (134,'Premium headphones that cost $200 or more','Device Usage',True);
INSERT INTO all_questions VALUES (135,'Digital radio','Device Usage',True);
INSERT INTO all_questions VALUES (136,'Smartwatch (e.g. Samsung Gear, Apple watch)','Device Usage',True);
INSERT INTO all_questions VALUES (137,'Fitness tracker (e.g. Fitbit, Garmin)','Device Usage',True);
INSERT INTO all_questions VALUES (138,'Smart Home speakers (e.g. Google Home, Amazon Echo)','Device Usage',True);
INSERT INTO all_questions VALUES (139,'Voice assistant (virtual assistants that can perform tasks or services based on verbal commands, e.g. Google, Siri, Alexa, Cortana)','Device Usage',True);
INSERT INTO all_questions VALUES (140,'Smart home extensions that use technology to control household appliances such as lights, sound systems and thermostats (e.g. NEST, smart heating thermostats, smart lightbulbs etc.)','Device Usage',True);
INSERT INTO all_questions VALUES (141,'Device Knowledge','NULL',False);
INSERT INTO all_questions VALUES (142,'Smartphones','Device Knowledge',True);
INSERT INTO all_questions VALUES (143,'Laptops/desktops','Device Knowledge',True);
INSERT INTO all_questions VALUES (144,'Sound and music devices','Device Knowledge',True);
INSERT INTO all_questions VALUES (145,'Video game consoles','Device Knowledge',True);
INSERT INTO all_questions VALUES (146,'TV screens/monitors','Device Knowledge',True);
INSERT INTO all_questions VALUES (147,'Technology in general','Device Knowledge',True);
INSERT INTO all_questions VALUES (148,'Technology Knowledge','NULL',False);
INSERT INTO all_questions VALUES (149,'Any smartphone can use 5G mobile data connections','Technology Knowledge',True);
INSERT INTO all_questions VALUES (150,'5G mobile connections can be as fast as 300 megabits per second','Technology Knowledge',True);
INSERT INTO all_questions VALUES (151,'The iPhone came out in 1998','Technology Knowledge',True);
INSERT INTO all_questions VALUES (152,'OS stands for Operational Server','Technology Knowledge',True);
INSERT INTO all_questions VALUES (153,'MP3 files are audio files','Technology Knowledge',True);
INSERT INTO all_questions VALUES (154,'CPU stands for Central Processing Unit','Technology Knowledge',True);
INSERT INTO all_questions VALUES (155,'Dolby provide the technology behind leading edge sound and vision devices','Technology Knowledge',True);
INSERT INTO all_questions VALUES (156,'All wireless speakers include Alexa','Technology Knowledge',True);
INSERT INTO all_questions VALUES (157,'Wireless headphones usually connect via Bluetooth','Technology Knowledge',True);
INSERT INTO all_questions VALUES (158,'4K TV has 4000 times the number of pixels that HD TV has','Technology Knowledge',True);
INSERT INTO all_questions VALUES (159,'The first PlayStation came out in the early 2000s','Technology Knowledge',True);
INSERT INTO all_questions VALUES (160,'More than 125 million people play Fortnite','Technology Knowledge',True);
INSERT INTO all_questions VALUES (161,'Artificial intelligence is already built into many smartphones','Technology Knowledge',True);
INSERT INTO all_questions VALUES (162,'Quantum computing can be up to 100 million times faster than regular computers','Technology Knowledge',True);
INSERT INTO all_questions VALUES (163,'Twitter is owned by Facebook','Technology Knowledge',True);
INSERT INTO all_questions VALUES (164,'Facebook are developing a digital currency called Ethereum','Technology Knowledge',True);
INSERT INTO all_questions VALUES (165,'95 million photos are uploaded to Instagram each day','Technology Knowledge',True);
INSERT INTO all_questions VALUES (166,'Future Technology','NULL',False);
INSERT INTO all_questions VALUES (167,'free up my time to do more of what I want to do','Future Technology',True);
INSERT INTO all_questions VALUES (168,'free us up from state control','Future Technology',True);
INSERT INTO all_questions VALUES (169,'put control in the hands of a few major corporations','Future Technology',True);
INSERT INTO all_questions VALUES (170,'take the power away from individuals','Future Technology',True);
INSERT INTO all_questions VALUES (171,'bring me closer to the people I care about','Future Technology',True);
INSERT INTO all_questions VALUES (172,'allow me to meet many more likeminded people','Future Technology',True);
INSERT INTO all_questions VALUES (173,'make real-life relationships weaker or harder to maintain','Future Technology',True);
INSERT INTO all_questions VALUES (174,'make us more isolated or lonely','Future Technology',True);
INSERT INTO all_questions VALUES (175,'make us all safer','Future Technology',True);
INSERT INTO all_questions VALUES (176,'give me more control over my life','Future Technology',True);
INSERT INTO all_questions VALUES (177,'make it easier for terrorists to make plans','Future Technology',True);
INSERT INTO all_questions VALUES (178,'open the door to new and frightening types of crime','Future Technology',True);
INSERT INTO all_questions VALUES (179,'help me learn new skills','Future Technology',True);
INSERT INTO all_questions VALUES (180,'allow me to be the person I want to be','Future Technology',True);
INSERT INTO all_questions VALUES (181,'make it hard to know what is true and what isn''t','Future Technology',True);
INSERT INTO all_questions VALUES (182,'make it harder to think and act as an individual','Future Technology',True);
INSERT INTO all_questions VALUES (183,'take jobs away from human beings','Future Technology',True);
INSERT INTO all_questions VALUES (184,'increase the divide between rich and poor','Future Technology',True);
INSERT INTO all_questions VALUES (185,'drive positive change in society','Future Technology',True);
INSERT INTO all_questions VALUES (186,'help solve the environmental problems the world faces','Future Technology',True);
INSERT INTO all_questions VALUES (187,'Opinions on Technology','NULL',False);
INSERT INTO all_questions VALUES (188,'I''m interested in technology and keep up to date with new developments in this area','Opinions on Technology',True);
INSERT INTO all_questions VALUES (189,'I trust technology firms with my personal information and dataI feel safe when using technology that I won''t fall victim to fraud or a scam','Opinions on Technology',True);
INSERT INTO all_questions VALUES (190,'I feel safe when using technology that I won''t fall victim to fraud or a scam','Opinions on Technology',True);
INSERT INTO all_questions VALUES (191,'When purchasing a new piece of technology, the brand that made it is important to me','Opinions on Technology',True);
INSERT INTO all_questions VALUES (192,'Most new technology is over-rated','Opinions on Technology',True);
INSERT INTO all_questions VALUES (193,'I''m worried about the impact new technology is having on the world','Opinions on Technology',True);
INSERT INTO all_questions VALUES (194,'Technological advancements are not as dramatic as they once were','Opinions on Technology',True);
INSERT INTO all_questions VALUES (195,'Technology and the internet allow me to get to the truth, the things the people in power don''t want you to know','Opinions on Technology',True);
INSERT INTO all_questions VALUES (196,'Technology Preferences','NULL',False);
INSERT INTO all_questions VALUES (197,'I''ll need to keep buying more devices until I''ll have everything I want','Technology Preferences',True);
INSERT INTO all_questions VALUES (198,'I prefer using newer technology even if it''s not proven','Technology Preferences',True);
INSERT INTO all_questions VALUES (199,'I make my own mind up whether the technology is worth buying or not','Technology Preferences',True);
INSERT INTO all_questions VALUES (200,'I trust that I know technology well enough to not need to read instructions','Technology Preferences',True);
INSERT INTO all_questions VALUES (201,'When it comes to gaming, I prefer to play the game myself','Technology Preferences',True);
INSERT INTO all_questions VALUES (202,'I''ll only upgrade if my older model stops working','Technology Preferences',True);
INSERT INTO all_questions VALUES (203,'Technology Profile','NULL',False);
INSERT INTO all_questions VALUES (204,'I enjoy reading about new technology products','Technology Profile',True);
INSERT INTO all_questions VALUES (205,'I''m willing to pay more for top quality electronics','Technology Profile',True);
INSERT INTO all_questions VALUES (206,'Before buying electronics, I do as much research as possible','Technology Profile',True);
INSERT INTO all_questions VALUES (207,'At first, I was nervous about using computers, but now I''m much more comfortable','Technology Profile',True);
INSERT INTO all_questions VALUES (208,'I want others to say "wow" when they see my electronics','Technology Profile',True);
INSERT INTO all_questions VALUES (209,'If I am to be able to use a new technology product, someone has to show me how to use it','Technology Profile',True);
INSERT INTO all_questions VALUES (210,'Building electronics is a hobby of mine','Technology Profile',True);
INSERT INTO all_questions VALUES (211,'I enjoy learning about technology or electronic products from others','Technology Profile',True);
INSERT INTO all_questions VALUES (212,'I like to have a lot of gadgets','Technology Profile',True);
INSERT INTO all_questions VALUES (213,'I often take the opportunity to discuss my knowledge of technology or electronic products with others','Technology Profile',True);
INSERT INTO all_questions VALUES (214,'Household Size','NULL',False);
INSERT INTO all_questions VALUES (215,'Household Composition','NULL',True);
INSERT INTO all_questions VALUES (216,'Personal Health','NULL',True);
INSERT INTO all_questions VALUES (217,'Children','NULL',True);
INSERT INTO all_questions VALUES (218,'Children education','NULL',True);
INSERT INTO all_questions VALUES (219,'Other''s Health','NULL',True);
INSERT INTO all_questions VALUES (220,'Main Occupation','NULL',True);
INSERT INTO all_questions VALUES (221,'Autocode Social Grade','NULL',True);
INSERT INTO all_questions VALUES (222,'Education','NULL',True);
INSERT INTO all_questions VALUES (223,'Residential Area','NULL',True);
INSERT INTO all_questions VALUES (224,'Autocode Urban Status','NULL',True);
INSERT INTO all_questions VALUES (225,'Region UK','NULL',True);
INSERT INTO all_questions VALUES (226,'Household Income UK','NULL',True);
INSERT INTO all_questions VALUES (227,'Ethnicity UK','NULL',True);
INSERT INTO all_questions VALUES (228,'State US','NULL',True);
INSERT INTO all_questions VALUES (229,'Region US','NULL',True);
INSERT INTO all_questions VALUES (230,'Household Income US','NULL',True);
INSERT INTO all_questions VALUES (231,'Ethnicity US','NULL',True);
INSERT INTO all_questions VALUES (232,'Ethnicity Group US','NULL',True);
SELECT * FROM all_questions;