DROP TABLE IF EXIST all_options;
CREATE TABLE all_options(
	QuestionID INT,
	OptionID INT,
	OptionText VARCHAR(255)
);
INSERT INTO all_options VALUES (1,1,'Wise Society panel');
INSERT INTO all_options VALUES (1,2,'Wesleyan panel');
INSERT INTO all_options VALUES (1,3,'GMI panel');
INSERT INTO all_options VALUES (2,1,'Under 18');
INSERT INTO all_options VALUES (2,2,'18-24');
INSERT INTO all_options VALUES (2,3,'25-34');
INSERT INTO all_options VALUES (2,4,'35-44');
INSERT INTO all_options VALUES (2,5,'45-54');
INSERT INTO all_options VALUES (2,6,'55-64');
INSERT INTO all_options VALUES (2,7,'65-74');
INSERT INTO all_options VALUES (2,8,'75+');
INSERT INTO all_options VALUES (3,1,'Male');
INSERT INTO all_options VALUES (3,2,'Female');
INSERT INTO all_options VALUES (3,3,'Other / Prefer not to say');
INSERT INTO all_options VALUES (4,1,'Single');
INSERT INTO all_options VALUES (4,2,'In a partnership');
INSERT INTO all_options VALUES (4,3,'Married / Civil partnership');
INSERT INTO all_options VALUES (4,4,'Divorced');
INSERT INTO all_options VALUES (4,5,'Widowed');
INSERT INTO all_options VALUES (4,6,'Prefer not to say');
INSERT INTO all_options VALUES (5,1,'Spouse/ partner');
INSERT INTO all_options VALUES (5,2,'Other adult 16+');
INSERT INTO all_options VALUES (5,3,'Child 11-15');
INSERT INTO all_options VALUES (5,4,'Child 7-10');
INSERT INTO all_options VALUES (5,5,'Child 0-6');
INSERT INTO all_options VALUES (5,6,'I live alone');
INSERT INTO all_options VALUES (6,1,'£0');
INSERT INTO all_options VALUES (6,2,'£1 - £19,999');
INSERT INTO all_options VALUES (6,3,'£20,000 - £39,999');
INSERT INTO all_options VALUES (6,4,'£40,000 - £59,999');
INSERT INTO all_options VALUES (6,5,'£60,000 - £74,999');
INSERT INTO all_options VALUES (6,6,'£75,000 - £99,999');
INSERT INTO all_options VALUES (6,7,'£100,000 - £149,999');
INSERT INTO all_options VALUES (6,8,'£150,000 - £199,999');
INSERT INTO all_options VALUES (6,9,'£200,000 - £499,999');
INSERT INTO all_options VALUES (6,10,'£500K +');
INSERT INTO all_options VALUES (6,11,'Don’t Know');
INSERT INTO all_options VALUES (6,12,'Prefer not to say');
INSERT INTO all_options VALUES (7,1,'£0 - £49,999');
INSERT INTO all_options VALUES (7,2,'£50,000 - £99,999');
INSERT INTO all_options VALUES (7,3,'£100,000 - £249,999');
INSERT INTO all_options VALUES (7,4,'£250,000 - £499,999');
INSERT INTO all_options VALUES (7,5,'£500,000 - £999,999');
INSERT INTO all_options VALUES (7,6,'£1m+');
INSERT INTO all_options VALUES (8,1,'High managerial');
INSERT INTO all_options VALUES (8,2,'Intermediate managerial');
INSERT INTO all_options VALUES (8,3,'Supervisor');
INSERT INTO all_options VALUES (8,4,'Skilled manual worker');
INSERT INTO all_options VALUES (8,5,'Semi-skilled manual worker');
INSERT INTO all_options VALUES (8,6,'Housewife/househusband');
INSERT INTO all_options VALUES (8,7,'Unemployed');
INSERT INTO all_options VALUES (8,8,'Student');
INSERT INTO all_options VALUES (8,9,'Retired and State Pension only');
INSERT INTO all_options VALUES (8,10,'Retired with Private Pension');
INSERT INTO all_options VALUES (8,11,'Non-working (other form of income)');
INSERT INTO all_options VALUES (9,1,'Marketing/ Advertising/ Market Research');
INSERT INTO all_options VALUES (9,2,'Banking/ Finance/ Insurance');
INSERT INTO all_options VALUES (9,3,'Journalism/ Public Relations');
INSERT INTO all_options VALUES (9,4,'Retail');
INSERT INTO all_options VALUES (9,5,'Manufacturing');
INSERT INTO all_options VALUES (9,6,'Government/ Public Sector');
INSERT INTO all_options VALUES (9,7,'Regulatory Body');
INSERT INTO all_options VALUES (9,8,'Charitable organisation/Third Sector');
INSERT INTO all_options VALUES (9,9,'Agriculture');
INSERT INTO all_options VALUES (9,10,'Construction');
INSERT INTO all_options VALUES (9,11,'Other (please specify)');
INSERT INTO all_options VALUES (10,1,'I do');
INSERT INTO all_options VALUES (10,2,'My partner and I do together');
INSERT INTO all_options VALUES (10,3,'Predominantly my partner');
INSERT INTO all_options VALUES (10,4,'Other');
INSERT INTO all_options VALUES (11,1,'Personal');
INSERT INTO all_options VALUES (11,2,'Company');
INSERT INTO all_options VALUES (11,3,'Final salary');
INSERT INTO all_options VALUES (11,4,'None');
INSERT INTO all_options VALUES (11,5,'Other (please specify)');
INSERT INTO all_options VALUES (12,1,'Actively managed');
INSERT INTO all_options VALUES (12,2,'Vague idea');
INSERT INTO all_options VALUES (12,3,'No idea');
INSERT INTO all_options VALUES (13,1,'ISA');
INSERT INTO all_options VALUES (13,2,'Property');
INSERT INTO all_options VALUES (13,3,'Cash');
INSERT INTO all_options VALUES (13,4,'Inheritance');
INSERT INTO all_options VALUES (13,5,'Other investments');
INSERT INTO all_options VALUES (19,1,'Don''t know');
INSERT INTO all_options VALUES (19,2,'Prefer not to answer');
INSERT INTO all_options VALUES (21,1,'1');
INSERT INTO all_options VALUES (21,2,'2');
INSERT INTO all_options VALUES (21,3,'3');
INSERT INTO all_options VALUES (21,4,'4');
INSERT INTO all_options VALUES (21,5,'5');
INSERT INTO all_options VALUES (22,1,'1');
INSERT INTO all_options VALUES (22,2,'2');
INSERT INTO all_options VALUES (22,3,'3');
INSERT INTO all_options VALUES (22,4,'4');
INSERT INTO all_options VALUES (22,5,'5');
INSERT INTO all_options VALUES (23,1,'1');
INSERT INTO all_options VALUES (23,2,'2');
INSERT INTO all_options VALUES (23,3,'3');
INSERT INTO all_options VALUES (23,4,'4');
INSERT INTO all_options VALUES (23,5,'5');
INSERT INTO all_options VALUES (28,1,'Very interested');
INSERT INTO all_options VALUES (28,2,'Quite interested');
INSERT INTO all_options VALUES (28,3,'Not very interested');
INSERT INTO all_options VALUES (28,4,'Not at all interested');
INSERT INTO all_options VALUES (29,1,'Yes – I am fully aware');
INSERT INTO all_options VALUES (29,2,'Yes – I have a broad understanding');
INSERT INTO all_options VALUES (29,3,'Not really');
INSERT INTO all_options VALUES (29,4,'Not at all');
INSERT INTO all_options VALUES (30,1,'Yes');
INSERT INTO all_options VALUES (30,2,'No');
INSERT INTO all_options VALUES (31,1,'Less than £10,000');
INSERT INTO all_options VALUES (31,2,'£10,000 - £20,000');
INSERT INTO all_options VALUES (31,3,'£20,000 - £30,000');
INSERT INTO all_options VALUES (31,4,'£30,000 - £40,000');
INSERT INTO all_options VALUES (31,5,'£40,000 or more');
INSERT INTO all_options VALUES (32,1,'49 or younger');
INSERT INTO all_options VALUES (32,2,'50-54');
INSERT INTO all_options VALUES (32,3,'55-59');
INSERT INTO all_options VALUES (32,4,'60-64');
INSERT INTO all_options VALUES (32,5,'65-69');
INSERT INTO all_options VALUES (32,6,'70+');
INSERT INTO all_options VALUES (32,7,'I don’t think I ever will retire');
INSERT INTO all_options VALUES (32,8,'I already am retired');
INSERT INTO all_options VALUES (33,1,'Retire');
INSERT INTO all_options VALUES (33,2,'Reduce work');
INSERT INTO all_options VALUES (33,3,'Continue to work');
INSERT INTO all_options VALUES (33,4,'Charitable work');
INSERT INTO all_options VALUES (34,1,'Very confident');
INSERT INTO all_options VALUES (34,2,'Quite confident');
INSERT INTO all_options VALUES (34,3,'Not very confident');
INSERT INTO all_options VALUES (34,4,'Not at all confident');
INSERT INTO all_options VALUES (36,1,'Not at all important');
INSERT INTO all_options VALUES (36,2,'Not very important');
INSERT INTO all_options VALUES (36,3,'Quite important');
INSERT INTO all_options VALUES (36,4,'Very important');
INSERT INTO all_options VALUES (36,5,'Not applicable');
INSERT INTO all_options VALUES (37,1,'Not at all important');
INSERT INTO all_options VALUES (37,2,'Not very important');
INSERT INTO all_options VALUES (37,3,'Quite important');
INSERT INTO all_options VALUES (37,4,'Very important');
INSERT INTO all_options VALUES (37,5,'Not applicable');
INSERT INTO all_options VALUES (38,1,'Not at all important');
INSERT INTO all_options VALUES (38,2,'Not very important');
INSERT INTO all_options VALUES (38,3,'Quite important');
INSERT INTO all_options VALUES (38,4,'Very important');
INSERT INTO all_options VALUES (38,5,'Not applicable');
INSERT INTO all_options VALUES (39,1,'Not at all important');
INSERT INTO all_options VALUES (39,2,'Not very important');
INSERT INTO all_options VALUES (39,3,'Quite important');
INSERT INTO all_options VALUES (39,4,'Very important');
INSERT INTO all_options VALUES (39,5,'Not applicable');
INSERT INTO all_options VALUES (40,1,'Manage investments');
INSERT INTO all_options VALUES (40,2,'Plan my financial future');
INSERT INTO all_options VALUES (40,3,'Plan my family''s financial future');
INSERT INTO all_options VALUES (40,4,'Manage money tax efficiently');
INSERT INTO all_options VALUES (40,5,'Understand savings and investments options');
INSERT INTO all_options VALUES (40,6,'Understand retirement options');
INSERT INTO all_options VALUES (40,7,'Knowing my finances are safe');
INSERT INTO all_options VALUES (40,8,'Other (please specify)');
INSERT INTO all_options VALUES (40,9,'None of these');
INSERT INTO all_options VALUES (41,1,'My bank or building society');
INSERT INTO all_options VALUES (41,2,'Another high street banks or building society');
INSERT INTO all_options VALUES (41,3,'A financial advisor');
INSERT INTO all_options VALUES (41,4,'An asset management company');
INSERT INTO all_options VALUES (41,5,'A provider specialising in pensions');
INSERT INTO all_options VALUES (41,6,'An online platform who offer pensions advice');
INSERT INTO all_options VALUES (41,7,'Other (please specify)');
INSERT INTO all_options VALUES (42,1,'Aviva');
INSERT INTO all_options VALUES (42,2,'AXA');
INSERT INTO all_options VALUES (42,3,'Columbia Threadneedle');
INSERT INTO all_options VALUES (42,4,'HSBC');
INSERT INTO all_options VALUES (42,5,'Legal & General');
INSERT INTO all_options VALUES (42,6,'Prudential');
INSERT INTO all_options VALUES (42,7,'Royal London');
INSERT INTO all_options VALUES (42,8,'St James Place');
INSERT INTO all_options VALUES (42,9,'Standard Life');
INSERT INTO all_options VALUES (42,10,'Wesleyan');
INSERT INTO all_options VALUES (42,11,'Other (please specify)');
INSERT INTO all_options VALUES (43,1,'Aviva');
INSERT INTO all_options VALUES (43,2,'AXA');
INSERT INTO all_options VALUES (43,3,'Columbia Threadneedle');
INSERT INTO all_options VALUES (43,4,'HSBC');
INSERT INTO all_options VALUES (43,5,'Legal & General');
INSERT INTO all_options VALUES (43,6,'Prudential');
INSERT INTO all_options VALUES (43,7,'Royal London');
INSERT INTO all_options VALUES (43,8,'St James Place');
INSERT INTO all_options VALUES (43,9,'Standard Life');
INSERT INTO all_options VALUES (43,10,'Wesleyan');
INSERT INTO all_options VALUES (43,11,'Other (please specify)');
INSERT INTO all_options VALUES (44,1,'Very - Fee most important');
INSERT INTO all_options VALUES (44,2,'Important - Prepared to pay for advice');
INSERT INTO all_options VALUES (44,3,'Not important - Quality most important');
INSERT INTO all_options VALUES (45,1,'Yes');
INSERT INTO all_options VALUES (45,2,'No');
INSERT INTO all_options VALUES (46,1,'Advisor makes all decisions');
INSERT INTO all_options VALUES (46,2,'Advisor makes most decisions');
INSERT INTO all_options VALUES (46,3,'Relies on advisor 50%');
INSERT INTO all_options VALUES (46,4,'Advisor makes half of all decisions');
INSERT INTO all_options VALUES (46,5,'Other (please specify)');
INSERT INTO all_options VALUES (47,1,'All investment advice');
INSERT INTO all_options VALUES (47,2,'Solely for pension’s advice');
INSERT INTO all_options VALUES (47,3,'Other (please specify)');
INSERT INTO all_options VALUES (48,1,'A person they trust');
INSERT INTO all_options VALUES (48,2,'Good investment performance');
INSERT INTO all_options VALUES (48,3,'Impartial investment advice');
INSERT INTO all_options VALUES (48,4,'Low fees');
INSERT INTO all_options VALUES (48,5,'Transparency on fees being charged');
INSERT INTO all_options VALUES (49,1,'Too expensive');
INSERT INTO all_options VALUES (49,2,'Enough knowledge');
INSERT INTO all_options VALUES (49,3,'Lack of trust');
INSERT INTO all_options VALUES (49,4,'Don''t know');
INSERT INTO all_options VALUES (49,5,'Other (please specify)');
INSERT INTO all_options VALUES (50,1,'Yes');
INSERT INTO all_options VALUES (50,2,'No');
INSERT INTO all_options VALUES (51,1,'Reliability');
INSERT INTO all_options VALUES (51,2,'Service');
INSERT INTO all_options VALUES (51,3,'Investment Proposition');
INSERT INTO all_options VALUES (51,4,'Saving Money');
INSERT INTO all_options VALUES (51,5,'Personal Understanding');
INSERT INTO all_options VALUES (51,6,'Personal Preference');
INSERT INTO all_options VALUES (51,7,'Tax Expertise');
INSERT INTO all_options VALUES (51,8,'Competitive Price');
INSERT INTO all_options VALUES (51,9,'Transparent Price');
INSERT INTO all_options VALUES (51,10,'Tax Savings');
INSERT INTO all_options VALUES (51,11,'Performance');
INSERT INTO all_options VALUES (51,12,'Impartial Advice');
INSERT INTO all_options VALUES (51,13,'Other (please specify)');
INSERT INTO all_options VALUES (52,1,'Never');
INSERT INTO all_options VALUES (52,2,'Every 5 years or so');
INSERT INTO all_options VALUES (52,3,'Annually');
INSERT INTO all_options VALUES (52,4,'More frequent than annually');
INSERT INTO all_options VALUES (53,1,'Specialist in pensions');
INSERT INTO all_options VALUES (53,2,'Broader financial advice');
INSERT INTO all_options VALUES (53,3,'Both');
INSERT INTO all_options VALUES (53,4,'It doesn’t matter');
INSERT INTO all_options VALUES (53,5,'Not applicable');
INSERT INTO all_options VALUES (54,1,'Yes');
INSERT INTO all_options VALUES (54,2,'No');
INSERT INTO all_options VALUES (55,1,'Looking forward');
INSERT INTO all_options VALUES (55,2,'Mostly looking forward');
INSERT INTO all_options VALUES (55,3,'Afraid');
INSERT INTO all_options VALUES (57,1,'1');
INSERT INTO all_options VALUES (57,2,'2');
INSERT INTO all_options VALUES (57,3,'3');
INSERT INTO all_options VALUES (57,4,'4');
INSERT INTO all_options VALUES (57,5,'5');
INSERT INTO all_options VALUES (57,6,'6');
INSERT INTO all_options VALUES (58,1,'1');
INSERT INTO all_options VALUES (58,2,'2');
INSERT INTO all_options VALUES (58,3,'3');
INSERT INTO all_options VALUES (58,4,'4');
INSERT INTO all_options VALUES (58,5,'5');
INSERT INTO all_options VALUES (58,6,'6');
INSERT INTO all_options VALUES (59,1,'1');
INSERT INTO all_options VALUES (59,2,'2');
INSERT INTO all_options VALUES (59,3,'3');
INSERT INTO all_options VALUES (59,4,'4');
INSERT INTO all_options VALUES (59,5,'5');
INSERT INTO all_options VALUES (59,6,'6');
INSERT INTO all_options VALUES (60,1,'1');
INSERT INTO all_options VALUES (60,2,'2');
INSERT INTO all_options VALUES (60,3,'3');
INSERT INTO all_options VALUES (60,4,'4');
INSERT INTO all_options VALUES (60,5,'5');
INSERT INTO all_options VALUES (60,6,'6');
INSERT INTO all_options VALUES (61,1,'1');
INSERT INTO all_options VALUES (61,2,'2');
INSERT INTO all_options VALUES (61,3,'3');
INSERT INTO all_options VALUES (61,4,'4');
INSERT INTO all_options VALUES (61,5,'5');
INSERT INTO all_options VALUES (61,6,'6');
INSERT INTO all_options VALUES (63,1,'1');
INSERT INTO all_options VALUES (63,2,'2');
INSERT INTO all_options VALUES (63,3,'3');
INSERT INTO all_options VALUES (63,4,'4');
INSERT INTO all_options VALUES (63,5,'5');
INSERT INTO all_options VALUES (63,6,'6');
INSERT INTO all_options VALUES (63,7,'7');
INSERT INTO all_options VALUES (64,1,'1');
INSERT INTO all_options VALUES (64,2,'2');
INSERT INTO all_options VALUES (64,3,'3');
INSERT INTO all_options VALUES (64,4,'4');
INSERT INTO all_options VALUES (64,5,'5');
INSERT INTO all_options VALUES (64,6,'6');
INSERT INTO all_options VALUES (64,7,'7');
INSERT INTO all_options VALUES (65,1,'1');
INSERT INTO all_options VALUES (65,2,'2');
INSERT INTO all_options VALUES (65,3,'3');
INSERT INTO all_options VALUES (65,4,'4');
INSERT INTO all_options VALUES (65,5,'5');
INSERT INTO all_options VALUES (65,6,'6');
INSERT INTO all_options VALUES (65,7,'7');
INSERT INTO all_options VALUES (66,1,'1');
INSERT INTO all_options VALUES (66,2,'2');
INSERT INTO all_options VALUES (66,3,'3');
INSERT INTO all_options VALUES (66,4,'4');
INSERT INTO all_options VALUES (66,5,'5');
INSERT INTO all_options VALUES (66,6,'6');
INSERT INTO all_options VALUES (66,7,'7');
INSERT INTO all_options VALUES (67,1,'1');
INSERT INTO all_options VALUES (67,2,'2');
INSERT INTO all_options VALUES (67,3,'3');
INSERT INTO all_options VALUES (67,4,'4');
INSERT INTO all_options VALUES (67,5,'5');
INSERT INTO all_options VALUES (67,6,'6');
INSERT INTO all_options VALUES (67,7,'7');
INSERT INTO all_options VALUES (68,1,'1');
INSERT INTO all_options VALUES (68,2,'2');
INSERT INTO all_options VALUES (68,3,'3');
INSERT INTO all_options VALUES (68,4,'4');
INSERT INTO all_options VALUES (68,5,'5');
INSERT INTO all_options VALUES (68,6,'6');
INSERT INTO all_options VALUES (68,7,'7');
INSERT INTO all_options VALUES (70,1,'1');
INSERT INTO all_options VALUES (70,2,'2');
INSERT INTO all_options VALUES (70,3,'3');
INSERT INTO all_options VALUES (70,4,'4');
INSERT INTO all_options VALUES (70,5,'5');
INSERT INTO all_options VALUES (71,1,'1');
INSERT INTO all_options VALUES (71,2,'2');
INSERT INTO all_options VALUES (71,3,'3');
INSERT INTO all_options VALUES (71,4,'4');
INSERT INTO all_options VALUES (71,5,'5');
INSERT INTO all_options VALUES (72,1,'1');
INSERT INTO all_options VALUES (72,2,'2');
INSERT INTO all_options VALUES (72,3,'3');
INSERT INTO all_options VALUES (72,4,'4');
INSERT INTO all_options VALUES (72,5,'5');
INSERT INTO all_options VALUES (73,1,'1');
INSERT INTO all_options VALUES (73,2,'2');
INSERT INTO all_options VALUES (73,3,'3');
INSERT INTO all_options VALUES (73,4,'4');
INSERT INTO all_options VALUES (73,5,'5');
INSERT INTO all_options VALUES (74,1,'1');
INSERT INTO all_options VALUES (74,2,'2');
INSERT INTO all_options VALUES (74,3,'3');
INSERT INTO all_options VALUES (74,4,'4');
INSERT INTO all_options VALUES (74,5,'5');
INSERT INTO all_options VALUES (75,1,'1');
INSERT INTO all_options VALUES (75,2,'2');
INSERT INTO all_options VALUES (75,3,'3');
INSERT INTO all_options VALUES (75,4,'4');
INSERT INTO all_options VALUES (75,5,'5');
INSERT INTO all_options VALUES (76,1,'1');
INSERT INTO all_options VALUES (76,2,'2');
INSERT INTO all_options VALUES (76,3,'3');
INSERT INTO all_options VALUES (76,4,'4');
INSERT INTO all_options VALUES (76,5,'5');
INSERT INTO all_options VALUES (77,1,'A lot more');
INSERT INTO all_options VALUES (77,2,'Little more');
INSERT INTO all_options VALUES (77,3,'Right amount');
INSERT INTO all_options VALUES (77,4,'Little less');
INSERT INTO all_options VALUES (77,5,'A lot less');
INSERT INTO all_options VALUES (84,1,'1');
INSERT INTO all_options VALUES (84,2,'2');
INSERT INTO all_options VALUES (84,3,'3');
INSERT INTO all_options VALUES (84,4,'4');
INSERT INTO all_options VALUES (84,5,'5');
INSERT INTO all_options VALUES (84,6,'6');
INSERT INTO all_options VALUES (84,7,'7');
INSERT INTO all_options VALUES (84,8,'8');
INSERT INTO all_options VALUES (85,1,'1');
INSERT INTO all_options VALUES (85,2,'2');
INSERT INTO all_options VALUES (85,3,'3');
INSERT INTO all_options VALUES (85,4,'4');
INSERT INTO all_options VALUES (85,5,'5');
INSERT INTO all_options VALUES (85,6,'6');
INSERT INTO all_options VALUES (85,7,'7');
INSERT INTO all_options VALUES (85,8,'8');
INSERT INTO all_options VALUES (86,1,'1');
INSERT INTO all_options VALUES (86,2,'2');
INSERT INTO all_options VALUES (86,3,'3');
INSERT INTO all_options VALUES (86,4,'4');
INSERT INTO all_options VALUES (86,5,'5');
INSERT INTO all_options VALUES (86,6,'6');
INSERT INTO all_options VALUES (86,7,'7');
INSERT INTO all_options VALUES (86,8,'8');
INSERT INTO all_options VALUES (87,1,'1');
INSERT INTO all_options VALUES (87,2,'2');
INSERT INTO all_options VALUES (87,3,'3');
INSERT INTO all_options VALUES (87,4,'4');
INSERT INTO all_options VALUES (87,5,'5');
INSERT INTO all_options VALUES (87,6,'6');
INSERT INTO all_options VALUES (87,7,'7');
INSERT INTO all_options VALUES (87,8,'8');
INSERT INTO all_options VALUES (88,1,'1');
INSERT INTO all_options VALUES (88,2,'2');
INSERT INTO all_options VALUES (88,3,'3');
INSERT INTO all_options VALUES (88,4,'4');
INSERT INTO all_options VALUES (88,5,'5');
INSERT INTO all_options VALUES (88,6,'6');
INSERT INTO all_options VALUES (88,7,'7');
INSERT INTO all_options VALUES (88,8,'8');
INSERT INTO all_options VALUES (89,1,'1');
INSERT INTO all_options VALUES (89,2,'2');
INSERT INTO all_options VALUES (89,3,'3');
INSERT INTO all_options VALUES (89,4,'4');
INSERT INTO all_options VALUES (89,5,'5');
INSERT INTO all_options VALUES (89,6,'6');
INSERT INTO all_options VALUES (89,7,'7');
INSERT INTO all_options VALUES (89,8,'8');
INSERT INTO all_options VALUES (90,1,'1');
INSERT INTO all_options VALUES (90,2,'2');
INSERT INTO all_options VALUES (90,3,'3');
INSERT INTO all_options VALUES (90,4,'4');
INSERT INTO all_options VALUES (90,5,'5');
INSERT INTO all_options VALUES (90,6,'6');
INSERT INTO all_options VALUES (90,7,'7');
INSERT INTO all_options VALUES (90,8,'8');
INSERT INTO all_options VALUES (91,1,'Retire early');
INSERT INTO all_options VALUES (91,2,'Better understanding');
INSERT INTO all_options VALUES (91,3,'Worry about care costs');
INSERT INTO all_options VALUES (91,4,'Contribution from employer');
INSERT INTO all_options VALUES (91,5,'Tax relief');
INSERT INTO all_options VALUES (91,6,'Other (please specify)');
INSERT INTO all_options VALUES (92,1,'Lack of confidence');
INSERT INTO all_options VALUES (92,2,'Complexity');
INSERT INTO all_options VALUES (92,3,'Lack of trust');
INSERT INTO all_options VALUES (92,4,'Fear of the future');
INSERT INTO all_options VALUES (92,5,'Financial jargon');
INSERT INTO all_options VALUES (92,6,'Cost of advice');
INSERT INTO all_options VALUES (92,7,'Uncertainty about my future');
INSERT INTO all_options VALUES (92,8,'Uncertainty about changes to the rules in the future');
INSERT INTO all_options VALUES (92,9,'Lack of information');
INSERT INTO all_options VALUES (92,10,'Lack of financial capacity');
INSERT INTO all_options VALUES (92,11,'Other (please specify)');
INSERT INTO all_options VALUES (94,1,'1');
INSERT INTO all_options VALUES (94,2,'2');
INSERT INTO all_options VALUES (94,3,'3');
INSERT INTO all_options VALUES (94,4,'4');
INSERT INTO all_options VALUES (94,5,'5');
INSERT INTO all_options VALUES (94,6,'6');
INSERT INTO all_options VALUES (94,7,'7');
INSERT INTO all_options VALUES (94,8,'8');
INSERT INTO all_options VALUES (94,9,'9');
INSERT INTO all_options VALUES (94,10,'10');
INSERT INTO all_options VALUES (95,1,'1');
INSERT INTO all_options VALUES (95,2,'2');
INSERT INTO all_options VALUES (95,3,'3');
INSERT INTO all_options VALUES (95,4,'4');
INSERT INTO all_options VALUES (95,5,'5');
INSERT INTO all_options VALUES (95,6,'6');
INSERT INTO all_options VALUES (95,7,'7');
INSERT INTO all_options VALUES (95,8,'8');
INSERT INTO all_options VALUES (95,9,'9');
INSERT INTO all_options VALUES (95,10,'10');
INSERT INTO all_options VALUES (96,1,'1');
INSERT INTO all_options VALUES (96,2,'2');
INSERT INTO all_options VALUES (96,3,'3');
INSERT INTO all_options VALUES (96,4,'4');
INSERT INTO all_options VALUES (96,5,'5');
INSERT INTO all_options VALUES (96,6,'6');
INSERT INTO all_options VALUES (96,7,'7');
INSERT INTO all_options VALUES (96,8,'8');
INSERT INTO all_options VALUES (96,9,'9');
INSERT INTO all_options VALUES (96,10,'10');
INSERT INTO all_options VALUES (97,1,'any age');
INSERT INTO all_options VALUES (97,2,'50+');
INSERT INTO all_options VALUES (97,3,'55+');
INSERT INTO all_options VALUES (97,4,'60+');
INSERT INTO all_options VALUES (97,5,'65+');
INSERT INTO all_options VALUES (97,6,'70+');
INSERT INTO all_options VALUES (97,7,'I don’t know');
INSERT INTO all_options VALUES (98,1,'None of it');
INSERT INTO all_options VALUES (98,2,'10%');
INSERT INTO all_options VALUES (98,3,'25%');
INSERT INTO all_options VALUES (98,4,'50%');
INSERT INTO all_options VALUES (98,5,'75%');
INSERT INTO all_options VALUES (98,6,'All of it');
INSERT INTO all_options VALUES (98,7,'I don’t know');
INSERT INTO all_options VALUES (99,1,'No tax');
INSERT INTO all_options VALUES (99,2,'All at the basic rate of tax');
INSERT INTO all_options VALUES (99,3,'First 25% tax free then the rest at your marginal tax rate');
INSERT INTO all_options VALUES (99,4,'50% tax free and the rest at your marginal tax rate');
INSERT INTO all_options VALUES (99,5,'All of it at your marginal tax rate');
INSERT INTO all_options VALUES (99,6,'None of these are correct');
INSERT INTO all_options VALUES (111,1,'Much better than before');
INSERT INTO all_options VALUES (111,2,'A little better than before');
INSERT INTO all_options VALUES (111,3,'About the same as before');
INSERT INTO all_options VALUES (111,4,'A little worse than before');
INSERT INTO all_options VALUES (111,5,'Much worse than before');
INSERT INTO all_options VALUES (111,6,'I don’t know');
INSERT INTO all_options VALUES (113,1,'1');
INSERT INTO all_options VALUES (113,2,'2');
INSERT INTO all_options VALUES (113,3,'3');
INSERT INTO all_options VALUES (113,4,'4');
INSERT INTO all_options VALUES (113,5,'5');
INSERT INTO all_options VALUES (114,1,'1');
INSERT INTO all_options VALUES (114,2,'2');
INSERT INTO all_options VALUES (114,3,'3');
INSERT INTO all_options VALUES (114,4,'4');
INSERT INTO all_options VALUES (114,5,'5');
INSERT INTO all_options VALUES (115,1,'1');
INSERT INTO all_options VALUES (115,2,'2');
INSERT INTO all_options VALUES (115,3,'3');
INSERT INTO all_options VALUES (115,4,'4');
INSERT INTO all_options VALUES (115,5,'5');
INSERT INTO all_options VALUES (116,1,'Likely to keep it invested as it is at the moment and make no changes');
INSERT INTO all_options VALUES (116,2,'Likely to change the funds it is invested in to less risky funds');
INSERT INTO all_options VALUES (116,3,'Likely to draw some cash and keep in a deposit account');
INSERT INTO all_options VALUES (116,4,'Likely to draw the majority of it out and keep as in a deposit account');
INSERT INTO all_options VALUES (116,5,'Likely to draw the majority out and invest elsewhere');
INSERT INTO all_options VALUES (116,6,'Likely to buy an annuity to guarantee some income for life');
INSERT INTO all_options VALUES (116,7,'No idea what to do with my pension');
INSERT INTO all_options VALUES (118,1,'1');
INSERT INTO all_options VALUES (118,2,'2');
INSERT INTO all_options VALUES (118,3,'3');
INSERT INTO all_options VALUES (118,4,'4');
INSERT INTO all_options VALUES (119,1,'1');
INSERT INTO all_options VALUES (119,2,'2');
INSERT INTO all_options VALUES (119,3,'3');
INSERT INTO all_options VALUES (119,4,'4');
INSERT INTO all_options VALUES (120,1,'1');
INSERT INTO all_options VALUES (120,2,'2');
INSERT INTO all_options VALUES (120,3,'3');
INSERT INTO all_options VALUES (120,4,'4');
INSERT INTO all_options VALUES (121,1,'1');
INSERT INTO all_options VALUES (121,2,'2');
INSERT INTO all_options VALUES (121,3,'3');
INSERT INTO all_options VALUES (121,4,'4');
INSERT INTO all_options VALUES (122,1,'The government');
INSERT INTO all_options VALUES (122,2,'Schools/ teachers');
INSERT INTO all_options VALUES (122,3,'The pension companies');
INSERT INTO all_options VALUES (122,4,'Financial Advisors');
INSERT INTO all_options VALUES (122,5,'Employers');
INSERT INTO all_options VALUES (122,6,'Other');
INSERT INTO all_options VALUES (123,1,'Government changing rules');
INSERT INTO all_options VALUES (123,2,'Good advice from advisors');
INSERT INTO all_options VALUES (123,3,'Good investments');
INSERT INTO all_options VALUES (123,4,'Investment companies making profit at my expense');
INSERT INTO all_options VALUES (123,5,'Correct decisions');
INSERT INTO all_options VALUES (123,6,'Overall market');
INSERT INTO all_options VALUES (124,1,'Better tax incentives');
INSERT INTO all_options VALUES (124,2,'Other matched contribution benefits');
INSERT INTO all_options VALUES (124,3,'Employer to provide better pensions');
INSERT INTO all_options VALUES (124,4,'Incentivise contributors');
INSERT INTO all_options VALUES (125,1,'A name I can trust');
INSERT INTO all_options VALUES (125,2,'Impartial advice');
INSERT INTO all_options VALUES (125,3,'Part of my employer scheme');
INSERT INTO all_options VALUES (125,4,'The fees and charges');
INSERT INTO all_options VALUES (125,5,'Information and education');
INSERT INTO all_options VALUES (127,1,'1');
INSERT INTO all_options VALUES (127,2,'2');
INSERT INTO all_options VALUES (127,3,'3');
INSERT INTO all_options VALUES (127,4,'4');
INSERT INTO all_options VALUES (127,5,'5');
INSERT INTO all_options VALUES (127,6,'6');
INSERT INTO all_options VALUES (127,7,'7');
INSERT INTO all_options VALUES (127,8,'8');
INSERT INTO all_options VALUES (128,1,'1');
INSERT INTO all_options VALUES (128,2,'2');
INSERT INTO all_options VALUES (128,3,'3');
INSERT INTO all_options VALUES (128,4,'4');
INSERT INTO all_options VALUES (128,5,'5');
INSERT INTO all_options VALUES (128,6,'6');
INSERT INTO all_options VALUES (128,7,'7');
INSERT INTO all_options VALUES (128,8,'8');
INSERT INTO all_options VALUES (129,1,'1');
INSERT INTO all_options VALUES (129,2,'2');
INSERT INTO all_options VALUES (129,3,'3');
INSERT INTO all_options VALUES (129,4,'4');
INSERT INTO all_options VALUES (129,5,'5');
INSERT INTO all_options VALUES (129,6,'6');
INSERT INTO all_options VALUES (129,7,'7');
INSERT INTO all_options VALUES (129,8,'8');
INSERT INTO all_options VALUES (130,1,'1');
INSERT INTO all_options VALUES (130,2,'2');
INSERT INTO all_options VALUES (130,3,'3');
INSERT INTO all_options VALUES (130,4,'4');
INSERT INTO all_options VALUES (130,5,'5');
INSERT INTO all_options VALUES (130,6,'6');
INSERT INTO all_options VALUES (130,7,'7');
INSERT INTO all_options VALUES (130,8,'8');
INSERT INTO all_options VALUES (131,1,'1');
INSERT INTO all_options VALUES (131,2,'2');
INSERT INTO all_options VALUES (131,3,'3');
INSERT INTO all_options VALUES (131,4,'4');
INSERT INTO all_options VALUES (131,5,'5');
INSERT INTO all_options VALUES (131,6,'6');
INSERT INTO all_options VALUES (131,7,'7');
INSERT INTO all_options VALUES (131,8,'8');
INSERT INTO all_options VALUES (132,1,'1');
INSERT INTO all_options VALUES (132,2,'2');
INSERT INTO all_options VALUES (132,3,'3');
INSERT INTO all_options VALUES (132,4,'4');
INSERT INTO all_options VALUES (132,5,'5');
INSERT INTO all_options VALUES (132,6,'6');
INSERT INTO all_options VALUES (132,7,'7');
INSERT INTO all_options VALUES (132,8,'8');
INSERT INTO all_options VALUES (133,1,'1');
INSERT INTO all_options VALUES (133,2,'2');
INSERT INTO all_options VALUES (133,3,'3');
INSERT INTO all_options VALUES (133,4,'4');
INSERT INTO all_options VALUES (133,5,'5');
INSERT INTO all_options VALUES (133,6,'6');
INSERT INTO all_options VALUES (133,7,'7');
INSERT INTO all_options VALUES (133,8,'8');
INSERT INTO all_options VALUES (134,1,'Very little');
INSERT INTO all_options VALUES (134,2,'Some');
INSERT INTO all_options VALUES (134,3,'A lot');
INSERT INTO all_options VALUES (135,1,'Greater needs');
INSERT INTO all_options VALUES (135,2,'No change');
INSERT INTO all_options VALUES (135,3,'Lesser need');
INSERT INTO all_options VALUES (136,1,'Risk not affordable');
INSERT INTO all_options VALUES (136,2,'No knowledge');
INSERT INTO all_options VALUES (136,3,'Too complicated');
INSERT INTO all_options VALUES (136,4,'Other (please specify)');
INSERT INTO all_options VALUES (137,1,'Already know how to fund retirement');
INSERT INTO all_options VALUES (137,2,'No complicated requirements');
INSERT INTO all_options VALUES (137,3,'Other (please specify)');
INSERT INTO all_options VALUES (139,1,'1');
INSERT INTO all_options VALUES (139,2,'2');
INSERT INTO all_options VALUES (139,3,'3');
INSERT INTO all_options VALUES (139,4,'4');
INSERT INTO all_options VALUES (139,5,'5');
INSERT INTO all_options VALUES (139,6,'6');
INSERT INTO all_options VALUES (139,7,'7');
INSERT INTO all_options VALUES (139,8,'8');
INSERT INTO all_options VALUES (139,9,'9');
INSERT INTO all_options VALUES (139,10,'10');
INSERT INTO all_options VALUES (140,1,'1');
INSERT INTO all_options VALUES (140,2,'2');
INSERT INTO all_options VALUES (140,3,'3');
INSERT INTO all_options VALUES (140,4,'4');
INSERT INTO all_options VALUES (140,5,'5');
INSERT INTO all_options VALUES (140,6,'6');
INSERT INTO all_options VALUES (140,7,'7');
INSERT INTO all_options VALUES (140,8,'8');
INSERT INTO all_options VALUES (140,9,'9');
INSERT INTO all_options VALUES (140,10,'10');
INSERT INTO all_options VALUES (141,1,'1');
INSERT INTO all_options VALUES (141,2,'2');
INSERT INTO all_options VALUES (141,3,'3');
INSERT INTO all_options VALUES (141,4,'4');
INSERT INTO all_options VALUES (141,5,'5');
INSERT INTO all_options VALUES (141,6,'6');
INSERT INTO all_options VALUES (141,7,'7');
INSERT INTO all_options VALUES (141,8,'8');
INSERT INTO all_options VALUES (141,9,'9');
INSERT INTO all_options VALUES (141,10,'10');
INSERT INTO all_options VALUES (142,1,'1');
INSERT INTO all_options VALUES (142,2,'2');
INSERT INTO all_options VALUES (142,3,'3');
INSERT INTO all_options VALUES (142,4,'4');
INSERT INTO all_options VALUES (142,5,'5');
INSERT INTO all_options VALUES (142,6,'6');
INSERT INTO all_options VALUES (142,7,'7');
INSERT INTO all_options VALUES (142,8,'8');
INSERT INTO all_options VALUES (142,9,'9');
INSERT INTO all_options VALUES (142,10,'10');
INSERT INTO all_options VALUES (143,1,'1');
INSERT INTO all_options VALUES (143,2,'2');
INSERT INTO all_options VALUES (143,3,'3');
INSERT INTO all_options VALUES (143,4,'4');
INSERT INTO all_options VALUES (143,5,'5');
INSERT INTO all_options VALUES (143,6,'6');
INSERT INTO all_options VALUES (143,7,'7');
INSERT INTO all_options VALUES (143,8,'8');
INSERT INTO all_options VALUES (143,9,'9');
INSERT INTO all_options VALUES (143,10,'10');
INSERT INTO all_options VALUES (144,1,'Base it on my current net salary per year x how many years I will be in retirement');
INSERT INTO all_options VALUES (144,2,'As much as affordable');
INSERT INTO all_options VALUES (144,3,'As much as needed today');
INSERT INTO all_options VALUES (144,4,'As much as might be needed in the future');
INSERT INTO all_options VALUES (144,5,'Do not calculate Single code');
INSERT INTO all_options VALUES (144,6,'Would not know how to calculate');
INSERT INTO all_options VALUES (145,1,'1 - No risk at all');
INSERT INTO all_options VALUES (145,2,'2');
INSERT INTO all_options VALUES (145,3,'3');
INSERT INTO all_options VALUES (145,4,'4');
INSERT INTO all_options VALUES (145,5,'5');
INSERT INTO all_options VALUES (145,6,'6');
INSERT INTO all_options VALUES (145,7,'7');
INSERT INTO all_options VALUES (145,8,'8');
INSERT INTO all_options VALUES (145,9,'9');
INSERT INTO all_options VALUES (145,10,'10 - A lot of risk');
INSERT INTO all_options VALUES (146,1,'Economic upturn');
INSERT INTO all_options VALUES (146,2,'Your pension delivering good growth returns');
INSERT INTO all_options VALUES (146,3,'Reduction in taxation');
INSERT INTO all_options VALUES (146,4,'Unexpected additional funds');
INSERT INTO all_options VALUES (146,5,'Investment pay off');
INSERT INTO all_options VALUES (146,6,'Job change');
INSERT INTO all_options VALUES (146,7,'Salary increase');
INSERT INTO all_options VALUES (147,1,'Economic downturn');
INSERT INTO all_options VALUES (147,2,'Pension reducing in value');
INSERT INTO all_options VALUES (147,3,'Loss on investment');
INSERT INTO all_options VALUES (147,4,'Tax increase');
INSERT INTO all_options VALUES (147,5,'Job loss');
INSERT INTO all_options VALUES (147,6,'Large expense');
INSERT INTO all_options VALUES (149,1,'1');
INSERT INTO all_options VALUES (149,2,'2');
INSERT INTO all_options VALUES (149,3,'3');
INSERT INTO all_options VALUES (149,4,'4');
INSERT INTO all_options VALUES (149,5,'5');
INSERT INTO all_options VALUES (150,1,'1');
INSERT INTO all_options VALUES (150,2,'2');
INSERT INTO all_options VALUES (150,3,'3');
INSERT INTO all_options VALUES (150,4,'4');
INSERT INTO all_options VALUES (150,5,'5');
INSERT INTO all_options VALUES (151,1,'1');
INSERT INTO all_options VALUES (151,2,'2');
INSERT INTO all_options VALUES (151,3,'3');
INSERT INTO all_options VALUES (151,4,'4');
INSERT INTO all_options VALUES (151,5,'5');
INSERT INTO all_options VALUES (152,1,'1');
INSERT INTO all_options VALUES (152,2,'2');
INSERT INTO all_options VALUES (152,3,'3');
INSERT INTO all_options VALUES (152,4,'4');
INSERT INTO all_options VALUES (152,5,'5');
INSERT INTO all_options VALUES (153,1,'1');
INSERT INTO all_options VALUES (153,2,'2');
INSERT INTO all_options VALUES (153,3,'3');
INSERT INTO all_options VALUES (153,4,'4');
INSERT INTO all_options VALUES (153,5,'5');
INSERT INTO all_options VALUES (154,1,'1');
INSERT INTO all_options VALUES (154,2,'2');
INSERT INTO all_options VALUES (154,3,'3');
INSERT INTO all_options VALUES (154,4,'4');
INSERT INTO all_options VALUES (154,5,'5');
INSERT INTO all_options VALUES (155,1,'1');
INSERT INTO all_options VALUES (155,2,'2');
INSERT INTO all_options VALUES (155,3,'3');
INSERT INTO all_options VALUES (155,4,'4');
INSERT INTO all_options VALUES (155,5,'5');
INSERT INTO all_options VALUES (156,1,'1');
INSERT INTO all_options VALUES (156,2,'2');
INSERT INTO all_options VALUES (156,3,'3');
INSERT INTO all_options VALUES (156,4,'4');
INSERT INTO all_options VALUES (156,5,'5');
INSERT INTO all_options VALUES (157,1,'1');
INSERT INTO all_options VALUES (157,2,'2');
INSERT INTO all_options VALUES (157,3,'3');
INSERT INTO all_options VALUES (157,4,'4');
INSERT INTO all_options VALUES (157,5,'5');
INSERT INTO all_options VALUES (158,1,'1');
INSERT INTO all_options VALUES (158,2,'2');
INSERT INTO all_options VALUES (158,3,'3');
INSERT INTO all_options VALUES (158,4,'4');
INSERT INTO all_options VALUES (158,5,'5');
INSERT INTO all_options VALUES (159,1,'1');
INSERT INTO all_options VALUES (159,2,'2');
INSERT INTO all_options VALUES (159,3,'3');
INSERT INTO all_options VALUES (159,4,'4');
INSERT INTO all_options VALUES (159,5,'5');
SELECT * FROM all_options;